# config to select component, the format is CONFIG_USE_${component}
# Please refer to cmake files below to get available components:
#  ${SdkRootDirPath}/devices/MKM35Z7/all_lib_device.cmake

set(CONFIG_COMPILER gcc)
set(CONFIG_TOOLCHAIN armgcc)
set(CONFIG_USE_COMPONENT_CONFIGURATION false)
set(CONFIG_USE_utility_debug_console_lite true)
set(CONFIG_USE_utility_assert_lite true)
set(CONFIG_USE_driver_pdb true)
set(CONFIG_USE_driver_port true)
set(CONFIG_USE_driver_clock true)
set(CONFIG_USE_driver_common true)
set(CONFIG_USE_device_MKM35Z7_CMSIS true)
set(CONFIG_USE_component_uart_adapter true)
set(CONFIG_USE_driver_uart true)
set(CONFIG_USE_component_lists true)
set(CONFIG_USE_device_MKM35Z7_startup true)
set(CONFIG_USE_driver_lpuart true)
set(CONFIG_USE_driver_irtc true)
set(CONFIG_USE_driver_smc true)
set(CONFIG_USE_driver_gpio true)
set(CONFIG_USE_utilities_misc_utilities true)
set(CONFIG_USE_utility_str true)
set(CONFIG_USE_CMSIS_Include_core_cm true)
set(CONFIG_USE_device_MKM35Z7_system true)
set(CONFIG_CORE cm0p)
set(CONFIG_DEVICE MKM35Z7)
set(CONFIG_BOARD twrkm35z75m)
set(CONFIG_KIT twrkm35z75m)
set(CONFIG_DEVICE_ID MKM35Z512xxx7)
set(CONFIG_FPU NO_FPU)
set(CONFIG_DSP NO_DSP)
