# config to select component, the format is CONFIG_USE_${component}
# Please refer to cmake files below to get available components:
#  ${SdkRootDirPath}/devices/MKE17Z7/all_lib_device.cmake

set(CONFIG_COMPILER gcc)
set(CONFIG_TOOLCHAIN armgcc)
set(CONFIG_USE_COMPONENT_CONFIGURATION false)
set(CONFIG_USE_utility_debug_console_lite true)
set(CONFIG_USE_utility_assert_lite true)
set(CONFIG_USE_driver_port true)
set(CONFIG_USE_driver_lptmr true)
set(CONFIG_USE_driver_gpio true)
set(CONFIG_USE_driver_clock true)
set(CONFIG_USE_driver_adc12 true)
set(CONFIG_USE_driver_trgmux true)
set(CONFIG_USE_driver_pmc true)
set(CONFIG_USE_driver_common true)
set(CONFIG_USE_device_MKE17Z7_CMSIS true)
set(CONFIG_USE_component_lpuart_adapter true)
set(CONFIG_USE_driver_lpuart true)
set(CONFIG_USE_component_lists true)
set(CONFIG_USE_device_MKE17Z7_startup true)
set(CONFIG_USE_driver_smc true)
set(CONFIG_USE_utilities_misc_utilities true)
set(CONFIG_USE_CMSIS_Include_core_cm true)
set(CONFIG_USE_device_MKE17Z7_system true)
set(CONFIG_CORE cm0p)
set(CONFIG_DEVICE MKE17Z7)
set(CONFIG_BOARD frdmke17z)
set(CONFIG_KIT frdmke17z)
set(CONFIG_DEVICE_ID MKE17Z256xxx7)
set(CONFIG_FPU NO_FPU)
set(CONFIG_DSP NO_DSP)
