# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_middleware_sdmmc_host_usdhc true)
set(CONFIG_USE_middleware_sdmmc_host_usdhc_interrupt_MIMXRT685S_cm33 true)
set(CONFIG_USE_middleware_fatfs_sd true)
set(CONFIG_USE_component_serial_manager_uart true)
set(CONFIG_USE_driver_flexcomm_usart true)
set(CONFIG_USE_middleware_usb_device_ip3511hs_MIMXRT685S_cm33 true)
set(CONFIG_USE_middleware_baremetal true)
set(MCUX_DEVICE "MIMXRT685S_cm33")