/*
 * Copyright (c) 2014-2016, Freescale Semiconductor, Inc.
 * Copyright 2016 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/*
 * Generated by erpcgen 1.9.0 on Thu Sep 23 10:39:09 2021.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_erpc_remote_control_h_)
#define _erpc_remote_control_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 10900 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

// Aliases data types declarations
typedef struct BoardConfig BoardConfig;
typedef struct AdcConfig AdcConfig;
typedef struct Vector Vector;

// Structures/unions data types declarations
//! Which peripherals are available on used board
struct BoardConfig
{
    bool DAC;
    bool MAG;
    bool RGB[3];
};

//! ADC peripheral configuration
struct AdcConfig
{
    float vref;
    float atomicSteps;
};

//! Struct for accelerometer and magnetometer peripherals
struct Vector
{
    int16_t A_x;
    int16_t A_y;
    int16_t A_z;
    int16_t M_x;
    int16_t M_y;
    int16_t M_z;
};


#endif // ERPC_TYPE_DEFINITIONS


#endif // _erpc_remote_control_h_
