# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_middleware_fatfs_usb true)
set(CONFIG_USE_component_serial_manager_uart true)
set(CONFIG_USE_driver_uart true)
set(CONFIG_USE_middleware_usb_host_ehci true)
set(CONFIG_USE_middleware_usb_host_khci true)
set(CONFIG_USE_middleware_usb_device_ehci true)
set(CONFIG_USE_middleware_usb_device_khci true)
set(CONFIG_USE_middleware_freertos-kernel_MK66F18 true)
set(MCUX_DEVICE "MK66F18")