# config to select component, the format is CONFIG_USE_${component}
# Please refer to cmake files below to get available components:
#  ${SdkRootDirPath}/devices/LPC824/all_lib_device.cmake

set(CONFIG_COMPILER gcc)
set(CONFIG_TOOLCHAIN armgcc)
set(CONFIG_USE_COMPONENT_CONFIGURATION false)
set(CONFIG_USE_utility_debug_console_lite true)
set(CONFIG_USE_utility_assert_lite true)
set(CONFIG_USE_driver_lpc_miniusart true)
set(CONFIG_USE_driver_common true)
set(CONFIG_USE_driver_clock true)
set(CONFIG_USE_driver_power_no_lib true)
set(CONFIG_USE_driver_lpc_gpio true)
set(CONFIG_USE_driver_inputmux true)
set(CONFIG_USE_driver_swm true)
set(CONFIG_USE_driver_syscon true)
set(CONFIG_USE_device_LPC824_CMSIS true)
set(CONFIG_USE_component_miniusart_adapter true)
set(CONFIG_USE_device_LPC824_startup true)
set(CONFIG_USE_driver_lpc_iocon_lite true)
set(CONFIG_USE_utilities_misc_utilities true)
set(CONFIG_USE_driver_reset true)
set(CONFIG_USE_driver_inputmux_connections true)
set(CONFIG_USE_driver_swm_connections true)
set(CONFIG_USE_driver_syscon_connections true)
set(CONFIG_USE_CMSIS_Include_core_cm true)
set(CONFIG_USE_device_LPC824_system true)
set(CONFIG_CORE cm0p)
set(CONFIG_DEVICE LPC824)
set(CONFIG_BOARD lpcxpresso824max)
set(CONFIG_KIT lpcxpresso824max)
set(CONFIG_DEVICE_ID LPC824)
set(CONFIG_FPU NO_FPU)
set(CONFIG_DSP NO_DSP)
