#ifndef _CLOCK_CONFIG_H_
#define _CLOCK_CONFIG_H_

#include "fsl_common.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/

#define BOARD_XTAL0_CLK_HZ 24000000U /*!< Board xtal0 frequency in Hz */

#define BOARD_XTAL32K_CLK_HZ 32768U  /*!< Board xtal32k frequency in Hz */

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes default configuration of clocks.
 *
 */
void BOARD_InitBootClocks(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 ***************** Configuration BOARD_BootClockOverDriveRUN *******************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for BOARD_BootClockOverDriveRUN configuration
 ******************************************************************************/
#if __CORTEX_M == 7
    #define BOARD_BOOTCLOCKRUN_CORE_CLOCK 792000000UL /*!< CM7 Core clock frequency: 792000000Hz */
#else
    #define BOARD_BOOTCLOCKRUN_CORE_CLOCK 392727272UL /*!< CM4 Core clock frequency: 392727272Hz */
#endif

/* Clock outputs (values are in Hz): */
#define BOARD_BOOTCLOCKOVERDRIVERUN_ACMP_CLK_ROOT     0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_ADC1_CLK_ROOT     88000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_ADC2_CLK_ROOT     88000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_ARM_PLL_CLK       792000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_ASRC_CLK_ROOT     24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_AXI_CLK_ROOT      792000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_BUS_CLK_ROOT      240000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_BUS_LPSR_CLK_ROOT 160000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_CAN1_CLK_ROOT     0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_CAN2_CLK_ROOT     0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_CAN3_CLK_ROOT     0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_CCM_CLKO1_CLK_ROOT24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_CCM_CLKO2_CLK_ROOT24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_CLK_1M            1000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_CSI2_CLK_ROOT     0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_CSI2_ESC_CLK_ROOT 0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_CSI2_UI_CLK_ROOT  0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_CSI_CLK_ROOT      0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_CSSYS_CLK_ROOT    24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_CSTRACE_CLK_ROOT  24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_ELCDIF_CLK_ROOT   24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_EMV1_CLK_ROOT     0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_EMV2_CLK_ROOT     0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_ENET1_CLK_ROOT    24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_ENET2_CLK_ROOT    24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_ENET_1G_REF_CLK   0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_ENET_1G_TX_CLK    24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_ENET_25M_CLK_ROOT 24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_ENET_QOS_CLK_ROOT 24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_ENET_QOS_REF_CLK  0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_ENET_QOS_TX_CLK   0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_ENET_REF_CLK      0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_ENET_TIMER1_CLK_ROOT24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_ENET_TIMER2_CLK_ROOT24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_ENET_TIMER3_CLK_ROOT24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_ENET_TX_CLK       0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_FLEXIO1_CLK_ROOT  120000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_FLEXIO2_CLK_ROOT  120000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_FLEXSPI1_CLK_ROOT 24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_FLEXSPI2_CLK_ROOT 24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_GC355_CLK_ROOT    24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_GPT1_CLK_ROOT     24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_GPT1_IPG_CLK_HIGHFREQ24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_GPT2_CLK_ROOT     24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_GPT2_IPG_CLK_HIGHFREQ24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_GPT3_CLK_ROOT     24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_GPT3_IPG_CLK_HIGHFREQ24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_GPT4_CLK_ROOT     24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_GPT4_IPG_CLK_HIGHFREQ24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_GPT5_CLK_ROOT     24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_GPT5_IPG_CLK_HIGHFREQ24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_GPT6_CLK_ROOT     24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_GPT6_IPG_CLK_HIGHFREQ24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LCDIFV2_CLK_ROOT  24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPI2C1_CLK_ROOT   0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPI2C2_CLK_ROOT   0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPI2C3_CLK_ROOT   66000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPI2C4_CLK_ROOT   0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPI2C5_CLK_ROOT   60000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPI2C6_CLK_ROOT   0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPSPI1_CLK_ROOT   0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPSPI2_CLK_ROOT   0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPSPI3_CLK_ROOT   0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPSPI4_CLK_ROOT   0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPSPI5_CLK_ROOT   0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPSPI6_CLK_ROOT   0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPUART10_CLK_ROOT 0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPUART11_CLK_ROOT 0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPUART12_CLK_ROOT 0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPUART1_CLK_ROOT  80000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPUART2_CLK_ROOT  0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPUART3_CLK_ROOT  0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPUART4_CLK_ROOT  0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPUART5_CLK_ROOT  0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPUART6_CLK_ROOT  80000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPUART7_CLK_ROOT  0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPUART8_CLK_ROOT  80000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_LPUART9_CLK_ROOT  0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_M4_CLK_ROOT       392727272UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_M4_SYSTICK_CLK_ROOT24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_M7_CLK_ROOT       792000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_M7_SYSTICK_CLK_ROOT24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_MIC_CLK_ROOT      24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_MIPI_DSI_TX_CLK_ESC_ROOT24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_MIPI_ESC_CLK_ROOT 24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_MIPI_REF_CLK_ROOT 24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_MQS_CLK_ROOT      0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_MQS_MCLK          0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_OSC_24M           24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_OSC_32K           32768UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_OSC_RC_16M        16000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_OSC_RC_400M       400000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_OSC_RC_48M        48000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_OSC_RC_48M_DIV2   24000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_PLL_AUDIO_CLK     672000025UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_PLL_AUDIO_SS_MODULATION0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_PLL_AUDIO_SS_RANGE0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_PLL_VIDEO_CLK     672000025UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_PLL_VIDEO_SS_MODULATION0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_PLL_VIDEO_SS_RANGE0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SAI1_CLK_ROOT     0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SAI1_MCLK1        0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SAI1_MCLK2        0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SAI1_MCLK3        0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SAI2_CLK_ROOT     0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SAI2_MCLK1        0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SAI2_MCLK2        0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SAI2_MCLK3        0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SAI3_CLK_ROOT     0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SAI3_MCLK1        0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SAI3_MCLK2        0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SAI3_MCLK3        0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SAI4_CLK_ROOT     0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SAI4_MCLK1        0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SAI4_MCLK2        0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SEMC_CLK_ROOT     0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SPDIF_CLK_ROOT    0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SPDIF_EXTCLK_OUT  0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SYS_PLL1_CLK      1000000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SYS_PLL1_DIV2_CLK 500000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SYS_PLL1_DIV5_CLK 200000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SYS_PLL1_SS_MODULATION0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SYS_PLL1_SS_RANGE 0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SYS_PLL2_CLK      528000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SYS_PLL2_PFD0_CLK 352000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SYS_PLL2_PFD1_CLK 594000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SYS_PLL2_PFD2_CLK 396000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SYS_PLL2_PFD3_CLK 297000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SYS_PLL2_SS_MODULATION0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SYS_PLL2_SS_RANGE 0UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SYS_PLL3_CLK      480000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SYS_PLL3_DIV2_CLK 240000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SYS_PLL3_PFD0_CLK 664615384UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SYS_PLL3_PFD1_CLK 508235294UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SYS_PLL3_PFD2_CLK 270000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_SYS_PLL3_PFD3_CLK 392727272UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_USDHC1_CLK_ROOT   200000000UL
#define BOARD_BOOTCLOCKOVERDRIVERUN_USDHC2_CLK_ROOT   0UL


/*******************************************************************************
 * API for BOARD_BootClockOverDriveRUN configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void BOARD_BootClockOverDriveRUN(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

#endif /* _CLOCK_CONFIG_H_ */

