/*
 * Copyright 2021, 2023 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);                    /* Function assigned for the Cortex-M7F */

/* GPIO_DISP_B2_13 (coord A5), PHY_RESET */
/* Routed pin properties */
#define ENET0_INITPINS_PHY_RESET_PERIPHERAL                               GPIO11   /*!< Peripheral name */
#define ENET0_INITPINS_PHY_RESET_SIGNAL                                  gpio_io   /*!< Signal name */
#define ENET0_INITPINS_PHY_RESET_CHANNEL                                     14U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define ENET0_INITPINS_PHY_RESET_GPIO                                     GPIO11   /*!< GPIO peripheral base pointer */
#define ENET0_INITPINS_PHY_RESET_GPIO_PIN                                    14U   /*!< GPIO pin number */
#define ENET0_INITPINS_PHY_RESET_GPIO_PIN_MASK                       (1U << 14U)   /*!< GPIO pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void ENET0_InitPins(void);                    /* Function assigned for the Cortex-M7F */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void ENET0_DeinitPins(void);                  /* Function assigned for the Cortex-M7F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
