/**
 *      This code is auto-generated and shall not be modified!
 */

#ifndef __SRTM_CONFIG_NN_H__
#define __SRTM_CONFIG_NN_H__

/**
 * @brief SRTM NN command fields
 */
typedef enum _srtm_rt600_nn_command
{
    SRTM_Command_xa_nn_matXvec_16x16_16,
    SRTM_Command_xa_nn_matXvec_16x16_32,
    SRTM_Command_xa_nn_matXvec_16x16_64,
    SRTM_Command_xa_nn_matXvec_16x16_16_tanh,
    SRTM_Command_xa_nn_matXvec_16x16_16_sigmoid,
    SRTM_Command_xa_nn_matXvec_batch_16x16_64,
    SRTM_Command_xa_nn_matXvec_8x16_16,
    SRTM_Command_xa_nn_matXvec_8x16_32,
    SRTM_Command_xa_nn_matXvec_8x16_64,
    SRTM_Command_xa_nn_matXvec_8x16_16_tanh,
    SRTM_Command_xa_nn_matXvec_8x16_16_sigmoid,
    SRTM_Command_xa_nn_matXvec_batch_8x16_64,
    SRTM_Command_xa_nn_matXvec_8x8_8,
    SRTM_Command_xa_nn_matXvec_8x8_16,
    SRTM_Command_xa_nn_matXvec_8x8_32,
    SRTM_Command_xa_nn_matXvec_8x8_8_tanh,
    SRTM_Command_xa_nn_matXvec_8x8_8_sigmoid,
    SRTM_Command_xa_nn_matXvec_batch_8x8_32,
    SRTM_Command_xa_nn_matXvec_f32xf32_f32_sigmoid,
    SRTM_Command_xa_nn_matXvec_f32xf32_f32_tanh,
    SRTM_Command_xa_nn_matXvec_f32xf32_f32,
    SRTM_Command_xa_nn_matXvec_batch_f32xf32_f32,
    SRTM_Command_xa_nn_vec_sigmoid_32_32,
    SRTM_Command_xa_nn_vec_tanh_32_32,
    SRTM_Command_xa_nn_vec_relu_32_32,
    SRTM_Command_xa_nn_vec_relu1_32_32,
    SRTM_Command_xa_nn_vec_relu6_32_32,
    SRTM_Command_xa_nn_vec_softmax_32_32,
    SRTM_Command_xa_nn_vec_sigmoid_f32_f32,
    SRTM_Command_xa_nn_vec_tanh_f32_f32,
    SRTM_Command_xa_nn_vec_relu_f32_f32,
    SRTM_Command_xa_nn_vec_relu1_f32_f32,
    SRTM_Command_xa_nn_vec_relu6_f32_f32,
    SRTM_Command_xa_nn_vec_softmax_f32_f32,
    SRTM_Command_xa_nn_vec_sigmoid_32_16,
    SRTM_Command_xa_nn_vec_tanh_32_16,
    SRTM_Command_xa_nn_vec_sigmoid_32_8,
    SRTM_Command_xa_nn_vec_tanh_32_8,
    SRTM_Command_xa_nn_vec_interpolation_q15,
    SRTM_Command_xa_nn_conv1d_std_getsize,
    SRTM_Command_xa_nn_conv1d_std_8x16,
    SRTM_Command_xa_nn_conv1d_std_8x8,
    SRTM_Command_xa_nn_conv1d_std_16x16,
    SRTM_Command_xa_nn_conv1d_std_f32,
    SRTM_Command_xa_nn_conv2d_std_getsize,
    SRTM_Command_xa_nn_conv2d_std_8x16,
    SRTM_Command_xa_nn_conv2d_std_8x8,
    SRTM_Command_xa_nn_conv2d_std_16x16,
    SRTM_Command_xa_nn_conv2d_std_f32,
    SRTM_Command_xa_nn_conv2d_depthwise_f32,
    SRTM_Command_xa_nn_conv2d_pointwise_f32,
    SRTM_Command_xa_nn_conv2d_depthwise_getsize,
    SRTM_Command_xa_nn_conv2d_pointwise_8x16,
    SRTM_Command_xa_nn_conv2d_pointwise_8x8,
    SRTM_Command_xa_nn_conv2d_depthwise_8x16,
    SRTM_Command_xa_nn_conv2d_depthwise_8x8,
    SRTM_Command_xa_nn_conv2d_depthwise_16x16,
    SRTM_Command_xa_nn_conv2d_pointwise_16x16,
    SRTM_Command_xa_nn_avgpool_getsize,
    SRTM_Command_xa_nn_avgpool_8,
    SRTM_Command_xa_nn_avgpool_16,
    SRTM_Command_xa_nn_avgpool_f32,
    SRTM_Command_xa_nn_maxpool_getsize,
    SRTM_Command_xa_nn_maxpool_8,
    SRTM_Command_xa_nn_maxpool_16,
    SRTM_Command_xa_nn_maxpool_f32,
    SRTM_Command_xa_nn_fully_connected_f32,
    SRTM_Command_xa_nn_fully_connected_16x16_16,
    SRTM_Command_xa_nn_fully_connected_8x16_16,
    SRTM_Command_xa_nn_fully_connected_8x8_8,
    SRTM_Command_NN_MAX,
} srtm_nn_command_t;

#endif // __SRTM_CONFIG_NN_H__
