/*
 * Copyright 2024 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v12.0
processor: MCXW716CxxxA
package_id: MCXW716CMFTA
mcu_data: ksdk2_0
processor_version: 0.12.6
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: '11', peripheral: LPUART0, signal: RX, pin_signal: ADC0_A12/PTA16/RF_NOT_ALLOWED/LPSPI0_PCS0/EWM0_OUT_b/LPI2C0_SCLS/TPM0_CH4/LPUART0_RX/RF_GPO_8/FLEXIO0_D5,
    pull_select: down, pull_enable: disable, slew_rate: fast, open_drain: disable, drive_strength: low}
  - {pin_num: '12', peripheral: LPUART0, signal: TX, pin_signal: ADC0_A13/PTA17/WUU0_P3/RF_NOT_ALLOWED/LPSPI0_SIN/EWM0_IN/LPI2C0_SDAS/TPM0_CH5/LPUART0_TX/RF_GPO_7/RF_GPO_8/FLEXIO0_D6,
    pull_select: down, pull_enable: disable, slew_rate: fast, open_drain: disable, drive_strength: low}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Clock Configuration: Peripheral clocks are enabled; module does not stall low power mode entry */
    CLOCK_EnableClock(kCLOCK_PortA);

    const port_pin_config_t porta16_pin11_config = {/* Internal pull-up/down resistor is disabled */
                                                    (uint16_t)kPORT_PullDisable,
                                                    /* Low internal pull resistor value is selected. */
                                                    (uint16_t)kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    (uint16_t)kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    (uint16_t)kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    (uint16_t)kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    (uint16_t)kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    (uint16_t)kPORT_NormalDriveStrength,
                                                    /* Pin is configured as LPUART0_RX */
                                                    (uint16_t)kPORT_MuxAlt6,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    (uint16_t)kPORT_UnlockRegister};
    /* PORTA16 (pin 11) is configured as LPUART0_RX */
    PORT_SetPinConfig(PORTA, 16U, &porta16_pin11_config);

    const port_pin_config_t porta17_pin12_config = {/* Internal pull-up/down resistor is disabled */
                                                    (uint16_t)kPORT_PullDisable,
                                                    /* Low internal pull resistor value is selected. */
                                                    (uint16_t)kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    (uint16_t)kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    (uint16_t)kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    (uint16_t)kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    (uint16_t)kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    (uint16_t)kPORT_NormalDriveStrength,
                                                    /* Pin is configured as LPUART0_TX */
                                                    (uint16_t)kPORT_MuxAlt6,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    (uint16_t)kPORT_UnlockRegister};
    /* PORTA17 (pin 12) is configured as LPUART0_TX */
    PORT_SetPinConfig(PORTA, 17U, &porta17_pin12_config);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
