/*
 * Copyright 2023 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v13.0
processor: MIMX8UD5xxx08
package_id: MIMX8UD5DVK08
mcu_data: ksdk2_0
processor_version: 0.13.4
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33}
- pin_list:
  - {pin_num: D2, peripheral: LPUART1, signal: lpuart_tx, pin_signal: PTA10, PS: UP, PE: ENABLED, SRE: STANDARD, ODE: PUSH_PULL, DSE: STANDARD, LK: UNLOCK, IBE: DISABLED,
    OBE: DISABLED, DFE: DISABLED, DFCS: IPGCLK, DFD: ZERO, INV: NotInvert}
  - {pin_num: C1, peripheral: LPUART1, signal: lpuart_rx, pin_signal: PTA11, PS: UP, PE: ENABLED}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {                                /*!< Function assigned for the core: Cortex-M33[cm33] */
    IOMUXC_SetPinMux(IOMUXC_PTA10_LPUART1_TX, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA10_LPUART1_TX,
                        IOMUXC_PCR_PE_MASK |
                        IOMUXC_PCR_PS_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTA11_LPUART1_RX, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA11_LPUART1_RX,
                        IOMUXC_PCR_PE_MASK |
                        IOMUXC_PCR_PS_MASK);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPsRamPins:
- options: {callFromInitBoot: 'false', coreID: cm33}
- pin_list:
  - {pin_num: D24, peripheral: FLEXSPI1, signal: flexspi_a_ss0_b, pin_signal: PTC17, DSE: HIDRIVE}
  - {pin_num: C25, peripheral: FLEXSPI1, signal: flexspi_a_sclk, pin_signal: PTC18, DSE: HIDRIVE}
  - {pin_num: A23, peripheral: FLEXSPI1, signal: flexspi_a_dqs, pin_signal: PTC12, PS: DOWN, PE: ENABLED, DSE: HIDRIVE}
  - {pin_num: D22, peripheral: FLEXSPI1, signal: 'flexspi_a_data, 7', pin_signal: PTC13, DSE: HIDRIVE}
  - {pin_num: B24, peripheral: FLEXSPI1, signal: 'flexspi_a_data, 6', pin_signal: PTC14, DSE: HIDRIVE}
  - {pin_num: A25, peripheral: FLEXSPI1, signal: 'flexspi_a_data, 5', pin_signal: PTC15, DSE: HIDRIVE}
  - {pin_num: F22, peripheral: FLEXSPI1, signal: 'flexspi_a_data, 4', pin_signal: PTC16, DSE: HIDRIVE}
  - {pin_num: D26, peripheral: FLEXSPI1, signal: 'flexspi_a_data, 3', pin_signal: PTC19, DSE: HIDRIVE}
  - {pin_num: B26, peripheral: FLEXSPI1, signal: 'flexspi_a_data, 2', pin_signal: PTC20, DSE: HIDRIVE}
  - {pin_num: F24, peripheral: FLEXSPI1, signal: 'flexspi_a_data, 1', pin_signal: PTC21, DSE: HIDRIVE}
  - {pin_num: E25, peripheral: FLEXSPI1, signal: 'flexspi_a_data, 0', pin_signal: PTC22, DSE: HIDRIVE}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPsRamPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPsRamPins(void) {                           /*!< Function assigned for the core: Cortex-M33[cm33] */
    IOMUXC_SetPinMux(IOMUXC_PTC12_FLEXSPI1_A_DQS, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTC12_FLEXSPI1_A_DQS,
                        IOMUXC_PCR_DSE_MASK |
                        IOMUXC_PCR_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTC13_FLEXSPI1_A_DATA7, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTC13_FLEXSPI1_A_DATA7,
                        IOMUXC_PCR_DSE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTC14_FLEXSPI1_A_DATA6, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTC14_FLEXSPI1_A_DATA6,
                        IOMUXC_PCR_DSE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTC15_FLEXSPI1_A_DATA5, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTC15_FLEXSPI1_A_DATA5,
                        IOMUXC_PCR_DSE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTC16_FLEXSPI1_A_DATA4, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTC16_FLEXSPI1_A_DATA4,
                        IOMUXC_PCR_DSE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTC17_FLEXSPI1_A_SS0_B, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTC17_FLEXSPI1_A_SS0_B,
                        IOMUXC_PCR_DSE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTC18_FLEXSPI1_A_SCLK, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTC18_FLEXSPI1_A_SCLK,
                        IOMUXC_PCR_DSE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTC19_FLEXSPI1_A_DATA3, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTC19_FLEXSPI1_A_DATA3,
                        IOMUXC_PCR_DSE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTC20_FLEXSPI1_A_DATA2, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTC20_FLEXSPI1_A_DATA2,
                        IOMUXC_PCR_DSE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTC21_FLEXSPI1_A_DATA1, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTC21_FLEXSPI1_A_DATA1,
                        IOMUXC_PCR_DSE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTC22_FLEXSPI1_A_DATA0, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTC22_FLEXSPI1_A_DATA0,
                        IOMUXC_PCR_DSE_MASK);
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
