/*
 * Copyright 2023 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v13.1
processor: MIMX8UD7xxx08
package_id: MIMX8UD7DVP08
mcu_data: ksdk2_0
processor_version: 0.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitDebugConsolePins();
    BOARD_InitPCA6414I2CPins();
    BOARD_InitEpdcPins();
    BOARD_InitEpdcI2CPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitDebugConsolePins:
- options: {callFromInitBoot: 'true', prefix: BOARD_, coreID: cm33}
- pin_list:
  - {pin_num: AH3, peripheral: LPUART1, signal: lpuart_rx, pin_signal: PTA11, PS: UP, PE: ENABLED}
  - {pin_num: AH2, peripheral: LPUART1, signal: lpuart_tx, pin_signal: PTA10, PS: UP, PE: ENABLED}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDebugConsolePins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitDebugConsolePins(void) {                    /*!< Function assigned for the core: Cortex-M33[cm33] */
    IOMUXC_SetPinMux(IOMUXC_PTA10_LPUART1_TX, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA10_LPUART1_TX,
                        IOMUXC_PCR_PE_MASK |
                        IOMUXC_PCR_PS_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTA11_LPUART1_RX, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA11_LPUART1_RX,
                        IOMUXC_PCR_PE_MASK |
                        IOMUXC_PCR_PS_MASK);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPCA6414I2CPins:
- options: {callFromInitBoot: 'true', coreID: cm33}
- pin_list:
  - {pin_num: AF4, peripheral: LPI2C0, signal: lpi2c_scl, pin_signal: PTA8, ODE: OPEN_DRAIN}
  - {pin_num: AG2, peripheral: LPI2C0, signal: lpi2c_sda, pin_signal: PTA9, ODE: OPEN_DRAIN}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPCA6414I2CPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPCA6414I2CPins(void) {                      /*!< Function assigned for the core: Cortex-M33[cm33] */
    IOMUXC_SetPinMux(IOMUXC_PTA8_LPI2C0_SCL, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA8_LPI2C0_SCL,
                        IOMUXC_PCR_ODE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTA9_LPI2C0_SDA, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA9_LPI2C0_SDA,
                        IOMUXC_PCR_ODE_MASK);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitEpdcPins:
- options: {callFromInitBoot: 'true', coreID: cm33}
- pin_list:
  - {pin_num: M2, peripheral: EPDC0, signal: 'epdc_d, 0', pin_signal: PTF23}
  - {pin_num: M4, peripheral: EPDC0, signal: 'epdc_d, 1', pin_signal: PTF22}
  - {pin_num: L2, peripheral: EPDC0, signal: 'epdc_d, 2', pin_signal: PTF21}
  - {pin_num: M6, peripheral: EPDC0, signal: 'epdc_d, 3', pin_signal: PTF20}
  - {pin_num: K1, peripheral: EPDC0, signal: 'epdc_d, 4', pin_signal: PTF19}
  - {pin_num: K4, peripheral: EPDC0, signal: 'epdc_d, 5', pin_signal: PTF18}
  - {pin_num: K2, peripheral: EPDC0, signal: 'epdc_d, 6', pin_signal: PTF17}
  - {pin_num: H2, peripheral: EPDC0, signal: 'epdc_d, 7', pin_signal: PTF16}
  - {pin_num: D6, peripheral: EPDC0, signal: epdc_pwrstat, pin_signal: PTE17}
  - {pin_num: D4, peripheral: EPDC0, signal: epdc_gdrl, pin_signal: PTE21}
  - {pin_num: M5, peripheral: EPDC0, signal: epdc_sdclk, pin_signal: PTF24}
  - {pin_num: M1, peripheral: EPDC0, signal: epdc_gdsp, pin_signal: PTF25}
  - {pin_num: N6, peripheral: EPDC0, signal: epdc_sdle, pin_signal: PTF26}
  - {pin_num: P1, peripheral: EPDC0, signal: 'epdc_sdce, 0', pin_signal: PTF27}
  - {pin_num: N4, peripheral: EPDC0, signal: 'epdc_sdce, 2', pin_signal: PTF30}
  - {pin_num: E4, peripheral: EPDC0, signal: epdc_sdoe, pin_signal: PTF0}
  - {pin_num: B3, peripheral: EPDC0, signal: epdc_gdclk, pin_signal: PTE19}
  - {pin_num: A2, peripheral: EPDC0, signal: epdc_gdoe, pin_signal: PTE20}
  - {pin_num: D5, peripheral: EPDC0, signal: epdc_pwrwake, pin_signal: PTE18}
  - {pin_num: AE4, peripheral: GPIOA, signal: 'pta, 3', pin_signal: PTA3}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitEpdcPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitEpdcPins(void) {                            /*!< Function assigned for the core: Cortex-M33[cm33] */
    IOMUXC_SetPinMux(IOMUXC_PTA3_PTA3, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTE17_EPDC0_PWRSTAT, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTE18_EPDC0_PWRWAKE, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTE19_EPDC0_GDCLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTE20_EPDC0_GDOE, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTE21_EPDC0_GDRL, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTF0_EPDC0_SDOE, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTF16_EPDC0_D7, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTF17_EPDC0_D6, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTF18_EPDC0_D5, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTF19_EPDC0_D4, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTF20_EPDC0_D3, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTF21_EPDC0_D2, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTF22_EPDC0_D1, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTF23_EPDC0_D0, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTF24_EPDC0_SDCLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTF25_EPDC0_GDSP, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTF26_EPDC0_SDLE, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTF27_EPDC0_SDCE0, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTF30_EPDC0_SDCE2, 0U);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitEpdcI2CPins:
- options: {callFromInitBoot: 'true', coreID: cm33}
- pin_list:
  - {pin_num: AE6, peripheral: LPI2C1, signal: lpi2c_scl, pin_signal: PTA12, ODE: OPEN_DRAIN}
  - {pin_num: AJ2, peripheral: LPI2C1, signal: lpi2c_sda, pin_signal: PTA13, ODE: OPEN_DRAIN}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitEpdcI2CPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitEpdcI2CPins(void) {                         /*!< Function assigned for the core: Cortex-M33[cm33] */
    IOMUXC_SetPinMux(IOMUXC_PTA12_LPI2C1_SCL, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA12_LPI2C1_SCL,
                        IOMUXC_PCR_ODE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTA13_LPI2C1_SDA, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA13_LPI2C1_SDA,
                        IOMUXC_PCR_ODE_MASK);
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
