# Copyright (c) 2014-2016, Freescale Semiconductor, Inc.
# Copyright 2016 NXP
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

#
# Generated by erpcgen 1.11.0 on Fri Apr 14 15:29:25 2023.
#
# AUTOGENERATED - DO NOT EDIT
#

