# config to select component, the format is CONFIG_USE_${component}
# Please refer to cmake files below to get available components:
#  ${SdkRootDirPath}/devices/K32L3A60/all_lib_device.cmake

set(CONFIG_COMPILER gcc)
set(CONFIG_TOOLCHAIN armgcc)
set(CONFIG_USE_COMPONENT_CONFIGURATION false)
set(CONFIG_USE_driver_lpi2c true)
set(CONFIG_USE_driver_tpm true)
set(CONFIG_USE_driver_fxos8700cq true)
set(CONFIG_USE_utility_debug_console_lite true)
set(CONFIG_USE_utility_assert_lite true)
set(CONFIG_USE_driver_gpio true)
set(CONFIG_USE_driver_port true)
set(CONFIG_USE_driver_clock true)
set(CONFIG_USE_driver_common true)
set(CONFIG_USE_driver_msmc true)
set(CONFIG_USE_driver_lpuart true)
set(CONFIG_USE_component_lpuart_adapter true)
set(CONFIG_USE_component_lists true)
set(CONFIG_USE_device_K32L3A60_CMSIS true)
set(CONFIG_USE_device_K32L3A60_startup true)
set(CONFIG_USE_utilities_misc_utilities true)
set(CONFIG_USE_utility_str true)
set(CONFIG_USE_CMSIS_Include_core_cm true)
set(CONFIG_USE_device_K32L3A60_system true)
set(CONFIG_CORE cm4f)
set(CONFIG_DEVICE K32L3A60)
set(CONFIG_BOARD frdmk32l3a6)
set(CONFIG_KIT frdmk32l3a6)
set(CONFIG_DEVICE_ID K32L3A60xxx)
set(CONFIG_FPU NO_FPU)
set(CONFIG_DSP NO_DSP)
set(CONFIG_CORE_ID cm4)
