/*
 * Copyright 2022-2023 NXP
 * All rights reserved.
 *
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
#include "app.h"
#include "fsl_flexspi.h"
#include "nor_flash.h"

/* For MX25UM51345G */
const uint32_t ReadLUTCmdSeq_MACRONIX[4] = {
    /*  Fast read with 4 bytes address(0x0c) */
    [4 * NOR_CMD_LUT_SEQ_IDX_READ + 0] =
        FLEXSPI_LUT_SEQ(kFLEXSPI_Command_SDR, kFLEXSPI_1PAD, SPINOR_OP_READ_FAST_4B, kFLEXSPI_Command_RADDR_SDR, kFLEXSPI_1PAD, SPINOR_ADDRESS_32_BITS),
    [4 * NOR_CMD_LUT_SEQ_IDX_READ + 1] = FLEXSPI_LUT_SEQ(
        kFLEXSPI_Command_DUMMY_SDR, kFLEXSPI_1PAD, SPINOR_DUMMY_CYCLE_NUMBER_0X8, kFLEXSPI_Command_READ_SDR, kFLEXSPI_1PAD, SPINOR_DATA_SIZE_4_BYTES),
};

const uint32_t OctalReadLUTCmdSeq_MACRONIX[4] = {
    /*  OPI DDR read */
    [4 * NOR_CMD_LUT_SEQ_IDX_READ + 0] =
        FLEXSPI_LUT_SEQ(kFLEXSPI_Command_DDR, kFLEXSPI_8PAD, SPINOR_OP_READ_DTR_0XEE_8_8_8_4B, kFLEXSPI_Command_DDR, kFLEXSPI_8PAD, SPINOR_OP_READ_DTR_0X11_8_8_8_4B),
    [4 * NOR_CMD_LUT_SEQ_IDX_READ + 1] = FLEXSPI_LUT_SEQ(
        kFLEXSPI_Command_RADDR_DDR, kFLEXSPI_8PAD, SPINOR_ADDRESS_32_BITS, kFLEXSPI_Command_DUMMY_DDR, kFLEXSPI_8PAD, SPINOR_DUMMY_CYCLE_NUMBER_0X29),
    [4 * NOR_CMD_LUT_SEQ_IDX_READ + 2] =
        FLEXSPI_LUT_SEQ(kFLEXSPI_Command_READ_DDR, kFLEXSPI_8PAD, SPINOR_DATA_SIZE_4_BYTES, kFLEXSPI_Command_STOP, kFLEXSPI_1PAD, 0x0),
};

const uint32_t LUTOctalMode_MACRONIX[CUSTOM_LUT_LENGTH] = {

    /* Read ID with SDR SPI Mode */
    [4 * NOR_CMD_LUT_SEQ_IDX_READID_SPI] = FLEXSPI_LUT_SEQ(kFLEXSPI_Command_SDR,
                                                           kFLEXSPI_1PAD,
                                                           SPINOR_OP_RDID,
                                                           kFLEXSPI_Command_READ_SDR,
                                                           kFLEXSPI_1PAD,
                                                           SPINOR_DATA_SIZE_4_BYTES),
    /*  OCTAL DTR read Mode(8DTRD) */
    [4 * NOR_CMD_LUT_SEQ_IDX_READ + 0] =
        FLEXSPI_LUT_SEQ(kFLEXSPI_Command_DDR, kFLEXSPI_8PAD, SPINOR_OP_READ_DTR_0XEE_8_8_8_4B, kFLEXSPI_Command_DDR, kFLEXSPI_8PAD, SPINOR_OP_READ_DTR_0X11_8_8_8_4B),
    [4 * NOR_CMD_LUT_SEQ_IDX_READ + 1] = FLEXSPI_LUT_SEQ(
        kFLEXSPI_Command_RADDR_DDR, kFLEXSPI_8PAD, SPINOR_ADDRESS_32_BITS, kFLEXSPI_Command_DUMMY_DDR, kFLEXSPI_8PAD, SPINOR_DUMMY_CYCLE_NUMBER_0X29),
    [4 * NOR_CMD_LUT_SEQ_IDX_READ + 2] =
        FLEXSPI_LUT_SEQ(kFLEXSPI_Command_READ_DDR, kFLEXSPI_8PAD, SPINOR_DATA_SIZE_4_BYTES, kFLEXSPI_Command_STOP, kFLEXSPI_1PAD, 0x0),

    /* Read status register SPI */
    [4 * NOR_CMD_LUT_SEQ_IDX_READSTATUS_SPI] =
        FLEXSPI_LUT_SEQ(kFLEXSPI_Command_SDR, kFLEXSPI_1PAD, SPINOR_OP_RDSR, kFLEXSPI_Command_READ_SDR, kFLEXSPI_1PAD, SPINOR_DATA_SIZE_4_BYTES),

    /* Write Enable SPI */
    [4 * NOR_CMD_LUT_SEQ_IDX_WRITEENABLE_SPI] =
        FLEXSPI_LUT_SEQ(kFLEXSPI_Command_SDR, kFLEXSPI_1PAD, SPINOR_OP_WREN, kFLEXSPI_Command_STOP, kFLEXSPI_1PAD, 0),

    /* Read ID OPI DTR */
    [4 * NOR_CMD_LUT_SEQ_IDX_READID_DTR_OPI] =
        FLEXSPI_LUT_SEQ(kFLEXSPI_Command_DDR, kFLEXSPI_8PAD, SPINOR_OP_RDID, kFLEXSPI_Command_DDR, kFLEXSPI_8PAD, SPINOR_OP_RDID2),
    [4 * NOR_CMD_LUT_SEQ_IDX_READID_DTR_OPI + 1] = FLEXSPI_LUT_SEQ(
        kFLEXSPI_Command_RADDR_DDR, kFLEXSPI_8PAD, SPINOR_ADDRESS_32_BITS, kFLEXSPI_Command_DUMMY_DDR, kFLEXSPI_8PAD, SPINOR_DUMMY_CYCLE_NUMBER_0X16),
    [4 * NOR_CMD_LUT_SEQ_IDX_READID_DTR_OPI + 2] =
        FLEXSPI_LUT_SEQ(kFLEXSPI_Command_READ_DDR, kFLEXSPI_8PAD, SPINOR_DATA_SIZE_4_BYTES, kFLEXSPI_Command_STOP, kFLEXSPI_1PAD, 0x0),

    /*  Write Enable OPI DTR */
    [4 * NOR_CMD_LUT_SEQ_IDX_WRITEENABLE_DTR_OPI] =
        FLEXSPI_LUT_SEQ(kFLEXSPI_Command_DDR, kFLEXSPI_8PAD, SPINOR_OP_WREN, kFLEXSPI_Command_DDR, kFLEXSPI_8PAD, SPINOR_OP_WREN_0XF9),

    /*  Erase Sector OPI DTR */
    [4 * NOR_CMD_LUT_SEQ_IDX_ERASESECTOR_DTR_OPI] =
        FLEXSPI_LUT_SEQ(kFLEXSPI_Command_DDR, kFLEXSPI_8PAD, SPINOR_OP_SE_4B_0X21, kFLEXSPI_Command_DDR, kFLEXSPI_8PAD, SPINOR_OP_SE_4B_0XDE),
    [4 * NOR_CMD_LUT_SEQ_IDX_ERASESECTOR_DTR_OPI + 1] =
        FLEXSPI_LUT_SEQ(kFLEXSPI_Command_RADDR_DDR, kFLEXSPI_8PAD, SPINOR_ADDRESS_32_BITS, kFLEXSPI_Command_STOP, kFLEXSPI_8PAD, 0),

    /*  Erase Chip OPI DTR */
    [4 * NOR_CMD_LUT_SEQ_IDX_CHIPERASE_DTR_OPI] =
        FLEXSPI_LUT_SEQ(kFLEXSPI_Command_DDR, kFLEXSPI_8PAD, SPINOR_OP_CHIP_ERASE, kFLEXSPI_Command_DDR, kFLEXSPI_8PAD, SPINOR_OP_CHIP_ERASE_0X9F),

    /*  Program OPI DTR */
    [4 * NOR_CMD_LUT_SEQ_IDX_PAGEPROGRAM_DTR_OPI] =
        FLEXSPI_LUT_SEQ(kFLEXSPI_Command_DDR, kFLEXSPI_8PAD, SPINOR_OP_PP_4B, kFLEXSPI_Command_DDR, kFLEXSPI_8PAD, SPINOR_OP_PP_4B_0XED),
    [4 * NOR_CMD_LUT_SEQ_IDX_PAGEPROGRAM_DTR_OPI + 1] = FLEXSPI_LUT_SEQ(
        kFLEXSPI_Command_RADDR_DDR, kFLEXSPI_8PAD, SPINOR_ADDRESS_32_BITS, kFLEXSPI_Command_WRITE_DDR, kFLEXSPI_8PAD, SPINOR_DATA_SIZE_4_BYTES),

    /* Enter OPI mode with SPI mode */
    [4 * NOR_CMD_LUT_SEQ_IDX_ENTEROPI] =
        FLEXSPI_LUT_SEQ(kFLEXSPI_Command_SDR, kFLEXSPI_1PAD, SPINOR_OP_WRCR2, kFLEXSPI_Command_RADDR_SDR, kFLEXSPI_1PAD, SPINOR_ADDRESS_32_BITS),
    [4 * NOR_CMD_LUT_SEQ_IDX_ENTEROPI + 1] =
        FLEXSPI_LUT_SEQ(kFLEXSPI_Command_WRITE_SDR, kFLEXSPI_1PAD, SPINOR_DATA_SIZE_4_BYTES, kFLEXSPI_Command_STOP, kFLEXSPI_1PAD, 0),

    /*  Dummy write, do nothing when AHB write command is triggered. */
    [4 * NOR_CMD_LUT_SEQ_IDX_WRITE] =
        FLEXSPI_LUT_SEQ(kFLEXSPI_Command_STOP, kFLEXSPI_1PAD, 0x0, kFLEXSPI_Command_STOP, kFLEXSPI_1PAD, 0x0),

    /*  Read status register OPI DTR */
    [4 * NOR_CMD_LUT_SEQ_IDX_READSTATUS_DTR_OPI] =
        FLEXSPI_LUT_SEQ(kFLEXSPI_Command_DDR, kFLEXSPI_8PAD, SPINOR_OP_RDSR, kFLEXSPI_Command_DDR, kFLEXSPI_8PAD, SPINOR_OP_RDSR_0XFA),
    [4 * NOR_CMD_LUT_SEQ_IDX_READSTATUS_DTR_OPI + 1] = FLEXSPI_LUT_SEQ(
        kFLEXSPI_Command_RADDR_DDR, kFLEXSPI_8PAD, SPINOR_ADDRESS_32_BITS, kFLEXSPI_Command_DUMMY_DDR, kFLEXSPI_8PAD, SPINOR_DUMMY_CYCLE_NUMBER_0X20),
    [4 * NOR_CMD_LUT_SEQ_IDX_READSTATUS_DTR_OPI + 2] =
        FLEXSPI_LUT_SEQ(kFLEXSPI_Command_READ_DDR, kFLEXSPI_8PAD, SPINOR_DATA_SIZE_4_BYTES, kFLEXSPI_Command_STOP, kFLEXSPI_1PAD, 0x0),

};
