/*
 * Copyright 2019-2020 NXP
 * All rights reserved.
 *
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/**
 *      This code is auto-generated and shall not be modified!
 */

#ifndef __SRTM_CONFIG_NN_H__
#define __SRTM_CONFIG_NN_H__

/**
 * @brief SRTM NN command fields
 */
typedef enum _srtm_rt600_nn_command
{
    SRTM_Command_xa_nn_matXvec_16x16_16,
    SRTM_Command_xa_nn_matXvec_16x16_32,
    SRTM_Command_xa_nn_matXvec_16x16_64,
    SRTM_Command_xa_nn_matXvec_16x16_16_tanh,
    SRTM_Command_xa_nn_matXvec_16x16_16_sigmoid,
    SRTM_Command_xa_nn_matXvec_batch_16x16_64,
    SRTM_Command_xa_nn_matmul_16x16_16,
    SRTM_Command_xa_nn_matXvec_8x16_16,
    SRTM_Command_xa_nn_matXvec_8x16_32,
    SRTM_Command_xa_nn_matXvec_8x16_64,
    SRTM_Command_xa_nn_matXvec_8x16_16_tanh,
    SRTM_Command_xa_nn_matXvec_8x16_16_sigmoid,
    SRTM_Command_xa_nn_matXvec_batch_8x16_64,
    SRTM_Command_xa_nn_matmul_8x16_16,
    SRTM_Command_xa_nn_matXvec_8x8_8,
    SRTM_Command_xa_nn_matXvec_8x8_16,
    SRTM_Command_xa_nn_matXvec_8x8_32,
    SRTM_Command_xa_nn_matXvec_8x8_8_tanh,
    SRTM_Command_xa_nn_matXvec_8x8_8_sigmoid,
    SRTM_Command_xa_nn_matXvec_batch_8x8_32,
    SRTM_Command_xa_nn_matmul_8x8_8,
    SRTM_Command_xa_nn_matXvec_f32xf32_f32_sigmoid,
    SRTM_Command_xa_nn_matXvec_f32xf32_f32_tanh,
    SRTM_Command_xa_nn_matXvec_f32xf32_f32,
    SRTM_Command_xa_nn_matXvec_batch_f32xf32_f32,
    SRTM_Command_xa_nn_matmul_f32xf32_f32,
    SRTM_Command_xa_nn_vec_sigmoid_32_32,
    SRTM_Command_xa_nn_vec_tanh_32_32,
    SRTM_Command_xa_nn_vec_relu_std_32_32,
    SRTM_Command_xa_nn_vec_relu_32_32,
    SRTM_Command_xa_nn_vec_relu1_32_32,
    SRTM_Command_xa_nn_vec_relu6_32_32,
    SRTM_Command_xa_nn_vec_softmax_32_32,
    SRTM_Command_xa_nn_vec_sigmoid_f32_f32,
    SRTM_Command_xa_nn_vec_tanh_f32_f32,
    SRTM_Command_xa_nn_vec_relu_f32_f32,
    SRTM_Command_xa_nn_vec_relu_std_f32_f32,
    SRTM_Command_xa_nn_vec_relu1_f32_f32,
    SRTM_Command_xa_nn_vec_relu6_f32_f32,
    SRTM_Command_xa_nn_vec_softmax_f32_f32,
    SRTM_Command_xa_nn_vec_sigmoid_32_16,
    SRTM_Command_xa_nn_vec_tanh_32_16,
    SRTM_Command_xa_nn_vec_sigmoid_32_8,
    SRTM_Command_xa_nn_vec_tanh_32_8,
    SRTM_Command_xa_nn_vec_relu_16_16,
    SRTM_Command_xa_nn_vec_relu_std_16_16,
    SRTM_Command_xa_nn_vec_relu_8_8,
    SRTM_Command_xa_nn_vec_relu_std_8_8,
    SRTM_Command_xa_nn_vec_interpolation_q15,
    SRTM_Command_xa_nn_conv1d_std_getsize,
    SRTM_Command_xa_nn_conv1d_std_8x16,
    SRTM_Command_xa_nn_conv1d_std_8x8,
    SRTM_Command_xa_nn_conv1d_std_16x16,
    SRTM_Command_xa_nn_conv1d_std_f32,
    SRTM_Command_xa_nn_conv2d_std_getsize,
    SRTM_Command_xa_nn_conv2d_std_8x16,
    SRTM_Command_xa_nn_conv2d_std_8x8,
    SRTM_Command_xa_nn_conv2d_std_16x16,
    SRTM_Command_xa_nn_conv2d_std_f32,
    SRTM_Command_xa_nn_conv2d_pointwise_f32,
    SRTM_Command_xa_nn_conv2d_pointwise_8x16,
    SRTM_Command_xa_nn_conv2d_pointwise_8x8,
    SRTM_Command_xa_nn_conv2d_depthwise_getsize,
    SRTM_Command_xa_nn_conv2d_depthwise_f32,
    SRTM_Command_xa_nn_conv2d_depthwise_8x16,
    SRTM_Command_xa_nn_conv2d_depthwise_8x8,
    SRTM_Command_xa_nn_conv2d_depthwise_16x16,
    SRTM_Command_xa_nn_conv2d_pointwise_16x16,
    SRTM_Command_xa_nn_avgpool_8,
    SRTM_Command_xa_nn_avgpool_16,
    SRTM_Command_xa_nn_avgpool_f32,
    SRTM_Command_xa_nn_avgpool_getsize,
    SRTM_Command_xa_nn_maxpool_f32,
    SRTM_Command_xa_nn_maxpool_getsize,
    SRTM_Command_xa_nn_maxpool_8,
    SRTM_Command_xa_nn_maxpool_16,
    SRTM_Command_xa_nn_fully_connected_f32,
    SRTM_Command_xa_nn_fully_connected_16x16_16,
    SRTM_Command_xa_nn_fully_connected_8x16_16,
    SRTM_Command_xa_nn_fully_connected_8x8_8,
    SRTM_Command_xa_nn_vec_activation_min_max_asym8_asym8,
    SRTM_Command_xa_nn_conv1d_std_asym8xasym8,
    SRTM_Command_xa_nn_conv2d_std_asym8xasym8,
    SRTM_Command_xa_nn_matXvec_asym8xasym8_asym8,
    SRTM_Command_xa_nn_matXvec_batch_asym8xasym8_asym8,
    SRTM_Command_xa_nn_matmul_asym8xasym8_asym8,
    SRTM_Command_xa_nn_conv2d_depthwise_asym8xasym8,
    SRTM_Command_xa_nn_conv2d_pointwise_asym8xasym8,
    SRTM_Command_xa_nn_vec_activation_min_max_f32_f32,
    SRTM_Command_xa_nn_maxpool_asym8,
    SRTM_Command_xa_nn_avgpool_asym8,
    SRTM_Command_xa_nn_fully_connected_asym8xasym8_asym8,
    SRTM_Command_xa_nn_elm_mul_f32xf32_f32,
    SRTM_Command_xa_nn_elm_add_f32xf32_f32,
    SRTM_Command_xa_nn_elm_mul_acc_f32xf32_f32,
    SRTM_Command_xa_nn_elm_sub_f32xf32_f32,
    SRTM_Command_xa_nn_elm_div_f32xf32_f32,
    SRTM_Command_xa_nn_elm_floor_f32_f32,
    SRTM_Command_xa_nn_elm_add_asym8xasym8_asym8,
    SRTM_Command_xa_nn_elm_mul_asym8xasym8_asym8,
    SRTM_Command_xa_nn_vec_softmax_asym8_asym8,
    SRTM_Command_xa_nn_vec_sigmoid_asym8_asym8,
    SRTM_Command_get_softmax_scratch_size,
    SRTM_Command_xa_nn_l2_norm_f32,
    SRTM_Command_xa_nn_dot_prod_f32xf32_f32,
    SRTM_Command_xa_nn_vec_activation_min_max_8_8,
    SRTM_Command_xa_nn_vec_activation_min_max_16_16,
    SRTM_Command_resizenearest_f32,
    SRTM_Command_resizenearest_8,
    SRTM_Command_NN_MAX,
} srtm_nn_command_t;

#endif // __SRTM_CONFIG_NN_H__
