# config to select component, the format is CONFIG_USE_${component}
# Please refer to cmake files below to get available components:
#  ${SdkRootDirPath}/devices/LPC54S018M/all_lib_device.cmake

set(CONFIG_COMPILER gcc)
set(CONFIG_TOOLCHAIN armgcc)
set(CONFIG_USE_COMPONENT_CONFIGURATION false)
set(CONFIG_USE_utility_debug_console_lite true)
set(CONFIG_USE_utility_assert_lite true)
set(CONFIG_USE_driver_gint true)
set(CONFIG_USE_driver_common true)
set(CONFIG_USE_driver_clock true)
set(CONFIG_USE_driver_power true)
set(CONFIG_USE_driver_lpc_iocon true)
set(CONFIG_USE_driver_lpc_gpio true)
set(CONFIG_USE_driver_inputmux true)
set(CONFIG_USE_device_LPC54S018M_CMSIS true)
set(CONFIG_USE_component_usart_adapter true)
set(CONFIG_USE_driver_flexcomm_usart true)
set(CONFIG_USE_component_lists true)
set(CONFIG_USE_device_LPC54S018M_startup true)
set(CONFIG_USE_driver_flexcomm true)
set(CONFIG_USE_driver_emc true)
set(CONFIG_USE_utilities_misc_utilities true)
set(CONFIG_USE_utility_str true)
set(CONFIG_USE_driver_reset true)
set(CONFIG_USE_driver_inputmux_connections true)
set(CONFIG_USE_CMSIS_Include_core_cm true)
set(CONFIG_USE_device_LPC54S018M_system true)
set(CONFIG_CORE cm4f)
set(CONFIG_DEVICE LPC54S018M)
set(CONFIG_BOARD lpcxpresso54s018m)
set(CONFIG_KIT lpcxpresso54s018m)
set(CONFIG_DEVICE_ID LPC54S018J4M)
set(CONFIG_FPU SP_FPU)
set(CONFIG_DSP NO_DSP)
