# config to select component, the format is CONFIG_USE_${component}
# Please refer to cmake files below to get available components:
#  ${SdkRootDirPath}/devices/K32W1480/all_lib_device.cmake

set(CONFIG_COMPILER gcc)
set(CONFIG_TOOLCHAIN armgcc)
set(CONFIG_USE_COMPONENT_CONFIGURATION false)
set(CONFIG_USE_middleware_freertos-kernel_cm33_non_trustzone true)
set(CONFIG_USE_middleware_freertos-kernel true)
set(CONFIG_USE_component_lists true)
set(CONFIG_USE_component_lpuart_adapter true)
set(CONFIG_USE_component_serial_manager true)
set(CONFIG_USE_component_serial_manager_uart true)
set(CONFIG_USE_device_K32W1480_CMSIS true)
set(CONFIG_USE_device_K32W1480_startup true)
set(CONFIG_USE_driver_ccm32k true)
set(CONFIG_USE_driver_clock true)
set(CONFIG_USE_driver_common true)
set(CONFIG_USE_driver_gpio true)
set(CONFIG_USE_driver_lpuart true)
set(CONFIG_USE_driver_port true)
set(CONFIG_USE_driver_spc true)
set(CONFIG_USE_utility_assert true)
set(CONFIG_USE_utility_debug_console true)
set(CONFIG_USE_utilities_misc_utilities true)
set(CONFIG_USE_middleware_freertos-kernel_template true)
set(CONFIG_USE_middleware_freertos-kernel_extension true)
set(CONFIG_USE_CMSIS_Include_core_cm true)
set(CONFIG_USE_device_K32W1480_system true)
set(CONFIG_USE_utility_str true)
set(CONFIG_CORE cm33)
set(CONFIG_DEVICE K32W1480)
set(CONFIG_BOARD k32w148evk)
set(CONFIG_KIT k32w148evk)
set(CONFIG_DEVICE_ID K32W1480xxxA)
set(CONFIG_FPU SP_FPU)
set(CONFIG_DSP DSP)
