# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_middleware_sdmmc_host_sdif true)
set(CONFIG_USE_middleware_sdmmc_host_sdif_freertos true)
set(CONFIG_USE_middleware_fatfs_sd true)
set(CONFIG_USE_component_serial_manager_uart true)
set(CONFIG_USE_driver_flexcomm_usart true)
set(CONFIG_USE_middleware_usb_host_ohci true)
set(CONFIG_USE_middleware_usb_host_ip3516hs_LPC54628 true)
set(CONFIG_USE_middleware_freertos-kernel_LPC54628 true)
set(MCUX_DEVICE "LPC54628")