#ifndef MBEDTLS_USER_CONFIG_H
#define MBEDTLS_USER_CONFIG_H

#undef MBEDTLS_DEBUG

#undef MBEDTLS_SSL_MAX_CONTENT_LEN
#define MBEDTLS_SSL_MAX_CONTENT_LEN (1024 * 16) 

#endif /* MBEDTLS_USER_CONFIG_H */
