/*
 * Copyright 2024 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v15.0
processor: RW612
package_id: RW612ETA2I
mcu_data: ksdk2_0
processor_version: 0.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_io_mux.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: F3, peripheral: FLEXCOMM3, signal: USART_RXD, pin_signal: GPIO_24}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : 
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void BOARD_InitPins(void)
{
    /* Initialize FC3_USART_DATA functionality on pin GPIO_24 (pin F3) */
    IO_MUX_SetPinMux(IO_MUX_FC3_USART_DATA);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
SPI0_InitPins:
- options: {callFromInitBoot: 'false', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: L4, peripheral: FLEXCOMM0, signal: SPI_MISO, pin_signal: GPIO_3, pull_up_down: disable}
  - {pin_num: U2, peripheral: FLEXCOMM0, signal: SPI_MOSI, pin_signal: GPIO_2, pull_up_down: disable}
  - {pin_num: N3, peripheral: FLEXCOMM0, signal: SPI_SCK, pin_signal: GPIO_4, pull_up_down: disable}
  - {pin_num: D12, peripheral: FLEXCOMM0, signal: SPI_SSELN0, pin_signal: GPIO_0, pull_up_down: disable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : SPI0_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void SPI0_InitPins(void)
{
    /* Initialize FC0_SPI_SS0 functionality on pin GPIO_3, GPIO_2, GPIO_4, GPIO_0 (pin L4_U2_N3_D12) */
    IO_MUX_SetPinMux(IO_MUX_FC0_SPI_SS0);
    /* Set GPIO_0 (pin L4_U2_N3_D12) configuration - Disable pull-up / pull-down; strongest slew rate */
    IO_MUX_SetPinConfig(0U, IO_MUX_PinConfigNoPull);
    /* Set GPIO_2 (pin L4_U2_N3_D12) configuration - Disable pull-up / pull-down; strongest slew rate */
    IO_MUX_SetPinConfig(2U, IO_MUX_PinConfigNoPull);
    /* Set GPIO_3 (pin L4_U2_N3_D12) configuration - Disable pull-up / pull-down; strongest slew rate */
    IO_MUX_SetPinConfig(3U, IO_MUX_PinConfigNoPull);
    /* Set GPIO_4 (pin L4_U2_N3_D12) configuration - Disable pull-up / pull-down; strongest slew rate */
    IO_MUX_SetPinConfig(4U, IO_MUX_PinConfigNoPull);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
SPI0_DeinitPins:
- options: {callFromInitBoot: 'false', coreID: cm33, enableClock: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : SPI0_DeinitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void SPI0_DeinitPins(void)
{
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
