# config to select component, the format is CONFIG_USE_${component}
# Please refer to cmake files below to get available components:
#  ${SdkRootDirPath}/devices/MKE02Z4/all_lib_device.cmake

set(CONFIG_COMPILER gcc)
set(CONFIG_TOOLCHAIN armgcc)
set(CONFIG_USE_COMPONENT_CONFIGURATION false)
set(CONFIG_USE_utility_debug_console_lite true)
set(CONFIG_USE_utility_assert_lite true)
set(CONFIG_USE_driver_ftm true)
set(CONFIG_USE_driver_clock true)
set(CONFIG_USE_driver_common true)
set(CONFIG_USE_device_MKE02Z4_CMSIS true)
set(CONFIG_USE_component_uart_adapter true)
set(CONFIG_USE_driver_uart true)
set(CONFIG_USE_component_lists true)
set(CONFIG_USE_device_MKE02Z4_startup true)
set(CONFIG_USE_driver_port_ke02 true)
set(CONFIG_USE_driver_gpio_1 true)
set(CONFIG_USE_utilities_misc_utilities true)
set(CONFIG_USE_CMSIS_Include_core_cm true)
set(CONFIG_USE_device_MKE02Z4_system true)
set(CONFIG_CORE cm0p)
set(CONFIG_DEVICE MKE02Z4)
set(CONFIG_BOARD frdmke02z40m)
set(CONFIG_KIT frdmke02z40m)
set(CONFIG_DEVICE_ID MKE02Z64xxx4)
set(CONFIG_FPU NO_FPU)
set(CONFIG_DSP NO_DSP)
