/*
 * Copyright 2022 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: TEE v4.0
processor: MIMXRT1166xxxxx
package_id: MIMXRT1166DVM6A
mcu_data: ksdk2_0
processor_version: 0.10.15
board: MIMXRT1160-EVK
toolOptions:
  _legacy_source_names_: 'no'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "resource_config.h"

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/* MPU region boundaries for BOARD_InitTEE function */
#define MPU_REGION_0_BASE 0x20360000U
#define MPU_REGION_0_END  0x2037FFFFU

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
functional_group:
- called_from_default_init: 'true'
- id_prefix: ''
- prefix_user_defined: 'true'
- name: 'BOARD_InitTEE'
- description: ''
- rdc:
  - xrdc2:
    - id: '0'
    - domains: [Domain 0, Domain 1]
    - masters:
      - master: {id: cm7_ahb, domain_assignments: [{enabled: 'true', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
      - master: {id: cm7_axi, domain_assignments: [{enabled: 'true', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '63'},
          {enabled: 'true', locked: 'false', domain_id: '1', secure: bypass, privileged: bypass, match_input: '64', mask_input: '63'}]}
      - master: {id: caam, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
      - master: {id: csi, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
      - master: {id: cm7_dma, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
      - master: {id: enet, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
      - master: {id: enet_1g_rx, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0',
            mask_input: '0'}]}
      - master: {id: enet_1g_tx, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0',
            mask_input: '0'}]}
      - master: {id: gc355, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
      - master: {id: lcdif1, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
      - master: {id: lcdifv2, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
      - master: {id: pxp, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
      - master: {id: ssarc, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass}]}
      - master: {id: usb, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
      - master: {id: usdhc1, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
      - master: {id: usdhc2, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
    - pacs:
      - pac:
        - checker_id: 'PAC'
        - slaves: [{id: MECC1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: MECC2, enabled: 'false',
            locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: XECC_FLEXSPI1, enabled: 'false', locked: unlock, eal: disabled,
            domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: XECC_FLEXSPI2, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: XECC_SEMC, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]},
          {id: FLEXRAM, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: EWM, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: WDOG1, enabled: 'true', locked: unlock, eal: disabled, domains: [{template: ALL},
              {template: NO_ACCESS}]}, {id: WDOG2, enabled: 'true', locked: unlock, eal: disabled, domains: [{template: ALL}, {template: NO_ACCESS}]}, {id: RTWDOG3,
            enabled: 'true', locked: unlock, eal: disabled, domains: [{template: ALL}, {template: NO_ACCESS}]}, {id: XBARA1, enabled: 'false', locked: unlock, eal: disabled,
            domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: XBARB2, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: XBARB3, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: ADC_ETC,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPADC1, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPADC2, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: DAC, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: IEE__IEE_RT1170,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: IEE_APC, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: DMA0, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: DMAMUX0, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {
            id: LPUART1, enabled: 'true', locked: unlock, eal: disabled, domains: [{template: ALL}, {template: ALL}]}, {id: LPUART2, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPUART3, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: LPUART4, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {
            id: LPUART5, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPUART6, enabled: 'false',
            locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPUART7, enabled: 'false', locked: unlock, eal: disabled,
            domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPUART8, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: LPUART9, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {
            id: LPUART10, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: FLEXIO1, enabled: 'false',
            locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: FLEXIO2, enabled: 'false', locked: unlock, eal: disabled,
            domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AOI1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: AOI2, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: CAN1,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: CAN2, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: FLEXSPI1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: FLEXSPI2, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {
            id: SEMC, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: PIT1, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: KPP, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: IOMUXC_GPR, enabled: 'true', locked: unlock, eal: disabled, domains: [{template: ALL}, {template: NO_ACCESS}]}, {id: IOMUXC,
            enabled: 'true', locked: unlock, eal: disabled, domains: [{template: ALL}, {template: NO_ACCESS}]}, {id: GPT1, enabled: 'false', locked: unlock, eal: disabled,
            domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPT2, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: GPT3, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPT4,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPT5, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPT6, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: LPI2C1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPI2C2,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPI2C3, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPI2C4, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: LPSPI1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPSPI2,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPSPI3, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPSPI4, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: GPIO1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPIO2,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPIO3, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPIO4, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: GPIO5, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPIO6,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: EMVSIM1, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: EMVSIM2, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: TMR1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: TMR2,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: TMR3, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: TMR4, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: ENC1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: ENC2,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: ENC3, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: ENC4, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: PWM1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: PWM2,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: PWM3, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: PWM4, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: CMP1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: CMP2,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: CMP3, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: CMP4, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: SPDIF, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: SAI1,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: SAI2, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: SAI3, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: ASRC, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: USDHC1,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: USDHC2, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: ENET_1G, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: ENET, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: USBHSDCD1,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: USB_OTG2, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: USB_OTG1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: USBPHY1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {
            id: USBPHY2, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: CSI, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LCDIF, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: LCDIFV2, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {
            id: DSI_HOST, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: MIPI_CSI2RX, enabled: 'false',
            locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: PXP, enabled: 'false', locked: unlock, eal: disabled, domains: [
              {template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: VIDEO_MUX, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {
                template: NO_ACCESS}]}, {id: GPC_SET_POINT_CTRL, enabled: 'true', locked: unlock, eal: disabled, domains: [{template: ALL}, {template: NO_ACCESS}]},
          {id: SRC, enabled: 'true', locked: unlock, eal: disabled, domains: [{template: ALL}, {template: NO_ACCESS}]}, {id: IOMUXC_LPSR, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: IOMUXC_LPSR_GPR, enabled: 'true', locked: unlock, eal: disabled, domains: [
              {template: ALL}, {template: NO_ACCESS}]}, {id: RTWDOG4, enabled: 'true', locked: unlock, eal: disabled, domains: [{template: ALL}, {template: NO_ACCESS}]},
          {id: DMA1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: DMAMUX1, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: PDM, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: LPUART11, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {
            id: LPUART12, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPSPI5, enabled: 'false',
            locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPSPI6, enabled: 'false', locked: unlock, eal: disabled,
            domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPI2C5, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: LPI2C6, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: CAN3,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: SAI4, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: RDC_SEMAPHORE1, enabled: 'false', locked: unlock, eal: disabled, domains: [
              {template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: MUA, enabled: 'true', locked: unlock, eal: disabled, domains: [{template: ALL}, {template: ALL}]},
          {id: MUB, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPIO7, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPIO8, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: GPIO9, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPIO10,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPIO11, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPIO12, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: RDC, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: KEY_MANAGER,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: ANADIG_MISC, enabled: 'true', locked: unlock,
            eal: disabled, domains: [{template: ALL}, {template: NO_ACCESS}]}, {id: PGMC_PPC0, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: SNVS, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: IOMUXC_SNVS,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: IOMUXC_SNVS_GPR, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: SRAM, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: GPIO13, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: ROMCP,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: DCDC, enabled: 'true', locked: unlock,
            eal: disabled, domains: [{template: ALL}, {template: NO_ACCESS}]}, {id: OCOTP, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: PIT2, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: SSARC_HP,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: SSARC_LP, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: CCM, enabled: 'true', locked: unlock, eal: disabled, domains: [{template: ALL},
              {template: NO_ACCESS}]}, {id: CCM_OBS, enabled: 'true', locked: unlock, eal: disabled, domains: [{template: ALL}, {template: NO_ACCESS}]}, {id: SEMA4,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: RDC_SEMAPHORE2, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: XRDC2_D1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: XRDC2_D0, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {
            id: GPU, base_region: {start: '0x00000000', size: '0x00100000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]},
          {id: CDOG, base_region: {start: '0x00000000', size: '0x00100000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]},
          {id: AIPSTZ2, base_region: {start: '0x00040000', size: '0x00010000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x00050000', size: '0x00010000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [
              {template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x00060000', size: '0x00010000'}, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x00070000', size: '0x00010000'}, enabled: 'false',
            locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x00080000', size: '0x00010000'},
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x00090000',
              size: '0x00010000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {
              start: '0x000A0000', size: '0x00010000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]},
          {id: AIPSTZ2, base_region: {start: '0x000B0000', size: '0x00010000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x000C0000', size: '0x00010000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [
              {template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x000D0000', size: '0x00010000'}, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x000E0000', size: '0x00010000'}, enabled: 'false',
            locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x000F0000', size: '0x00010000'},
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x00100000',
              size: '0x00010000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {
              start: '0x00110000', size: '0x00010000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]},
          {id: AIPSTZ2, base_region: {start: '0x00120000', size: '0x00010000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x00130000', size: '0x00010000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [
              {template: NO_ACCESS}, {template: NO_ACCESS}]}]
    - mscs:
      - msc:
        - checker_id: 'MSC'
        - slaves: [{id: SIM_DISP, base_region: {start: '0x00000000', size: '0x00100000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: SIM_M4, base_region: {start: '0x00000000', size: '0x00100000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [
              {template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: SIM_M7, base_region: {start: '0x00000000', size: '0x00100000'}, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: ROMCP, base_region: {start: '0x00000000', size: '0x00040000'}, enabled: 'false',
            locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}]
    - mrcs:
      - mrc:
        - checker_id: 'MRC'
        - slaves: [{id: SRAM_OC_cm4, base_region: {start: '0x00000000', size: '0x00040000'}, enabled: 'true', locked: unlock, eal: disabled, index: '0', domains: [
              {template: ALL}, {template: ALL}]}, {id: SRAM_OC_ECC1, base_region: {start: '0x00000000', size: '0x00010000'}, enabled: 'true', locked: unlock, eal: disabled,
            index: '0', domains: [{template: ALL}, {template: ALL}]}, {id: SRAM_OC_cm7, base_region: {start: '0x00000000', size: '0x00020000'}, enabled: 'true', locked: unlock,
            eal: disabled, index: '0', domains: [{template: ALL}, {template: NO_ACCESS}]}, {id: SRAM_OC_ECC2, base_region: {start: '0x00000000', size: '0x00010000'},
            enabled: 'true', locked: unlock, eal: disabled, index: '0', domains: [{template: ALL}, {template: ALL}]}, {id: CAAM, base_region: {start: '0x00000000',
              size: '0x00010000'}, enabled: 'true', locked: unlock, eal: disabled, index: '0', domains: [{template: ALL}, {template: ALL}]}, {id: SEMC, base_region: {
              start: '0x00000000', size: '0x04000000'}, enabled: 'true', locked: unlock, eal: disabled, index: '0', domains: [{template: ALL}, {template: ALL}]},
          {id: FLEXSPI1_REGION, base_region: {start: '0x00000000', size: '0x01000000'}, enabled: 'true', locked: unlock, eal: disabled, index: '0', domains: [{template: ALL},
              {template: ALL}]}, {id: FLEXSPI2_REGION, base_region: {start: '0x00000000', size: '0x02000000'}, enabled: 'false', locked: unlock, eal: disabled, index: '0',
            domains: [{template: ALL}, {template: ALL}]}]
  - xrdc2:
    - id: '1'
    - domains: [Domain 0, Domain 1]
    - masters:
      - master: {id: cm4_ahbc, domain_assignments: [{enabled: 'true', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '63'},
          {enabled: 'true', locked: 'false', domain_id: '1', secure: bypass, privileged: bypass, match_input: '64', mask_input: '63'}]}
      - master: {id: cm4_ahbs, domain_assignments: [{enabled: 'true', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '63'},
          {enabled: 'true', locked: 'false', domain_id: '1', secure: bypass, privileged: bypass, match_input: '64', mask_input: '63'}]}
      - master: {id: caam, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
      - master: {id: csi, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
      - master: {id: cm4_dma, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
      - master: {id: enet, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
      - master: {id: enet_1g_rx, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0',
            mask_input: '0'}]}
      - master: {id: enet_1g_tx, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0',
            mask_input: '0'}]}
      - master: {id: gc355, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
      - master: {id: lcdif1, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
      - master: {id: lcdifv2, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
      - master: {id: pxp, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
      - master: {id: ssarc, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass}]}
      - master: {id: usb, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
      - master: {id: usdhc1, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
      - master: {id: usdhc2, domain_assignments: [{enabled: 'false', locked: 'false', domain_id: '0', secure: bypass, privileged: bypass, match_input: '0', mask_input: '0'}]}
    - pacs:
      - pac:
        - checker_id: 'PAC'
        - slaves: [{id: MECC1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: MECC2, enabled: 'false',
            locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: XECC_FLEXSPI1, enabled: 'false', locked: unlock, eal: disabled,
            domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: XECC_FLEXSPI2, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: XECC_SEMC, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]},
          {id: FLEXRAM, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: EWM, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: WDOG1, enabled: 'true', locked: unlock, eal: disabled, domains: [{template: ALL},
              {template: NO_ACCESS}]}, {id: WDOG2, enabled: 'true', locked: unlock, eal: disabled, domains: [{template: ALL}, {template: NO_ACCESS}]}, {id: RTWDOG3,
            enabled: 'true', locked: unlock, eal: disabled, domains: [{template: ALL}, {template: NO_ACCESS}]}, {id: XBARA1, enabled: 'false', locked: unlock, eal: disabled,
            domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: XBARB2, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: XBARB3, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: ADC_ETC,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPADC1, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPADC2, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: DAC, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: IEE__IEE_RT1170,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: IEE_APC, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: DMA0, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: DMAMUX0, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {
            id: LPUART1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPUART2, enabled: 'false',
            locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPUART3, enabled: 'false', locked: unlock, eal: disabled,
            domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPUART4, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: LPUART5, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {
            id: LPUART6, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPUART7, enabled: 'false',
            locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPUART8, enabled: 'false', locked: unlock, eal: disabled,
            domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPUART9, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: LPUART10, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {
            id: FLEXIO1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: FLEXIO2, enabled: 'false',
            locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AOI1, enabled: 'false', locked: unlock, eal: disabled, domains: [
              {template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AOI2, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]},
          {id: CAN1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: CAN2, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: FLEXSPI1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: FLEXSPI2, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {
            id: SEMC, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: PIT1, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: KPP, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: IOMUXC_GPR, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]},
          {id: IOMUXC, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPT1, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPT2, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: GPT3, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPT4,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPT5, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPT6, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: LPI2C1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPI2C2,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPI2C3, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPI2C4, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: LPSPI1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPSPI2,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPSPI3, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPSPI4, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: GPIO1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPIO2,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPIO3, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPIO4, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: GPIO5, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPIO6,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: EMVSIM1, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: EMVSIM2, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: TMR1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: TMR2,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: TMR3, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: TMR4, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: ENC1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: ENC2,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: ENC3, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: ENC4, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: PWM1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: PWM2,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: PWM3, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: PWM4, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: CMP1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: CMP2,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: CMP3, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: CMP4, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: SPDIF, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: SAI1,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: SAI2, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: SAI3, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: ASRC, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: USDHC1,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: USDHC2, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: ENET_1G, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: ENET, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: USBHSDCD1,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: USB_OTG2, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: USB_OTG1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: USBPHY1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {
            id: USBPHY2, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: CSI, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LCDIF, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: LCDIFV2, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {
            id: DSI_HOST, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: MIPI_CSI2RX, enabled: 'false',
            locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: PXP, enabled: 'false', locked: unlock, eal: disabled, domains: [
              {template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: VIDEO_MUX, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {
                template: NO_ACCESS}]}, {id: GPC_SET_POINT_CTRL, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]},
          {id: SRC, enabled: 'true', locked: unlock, eal: disabled, domains: [{template: ALL}, {template: NO_ACCESS}]}, {id: IOMUXC_LPSR, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: IOMUXC_LPSR_GPR, enabled: 'true', locked: unlock, eal: disabled, domains: [
              {template: ALL}, {template: NO_ACCESS}]}, {id: RTWDOG4, enabled: 'true', locked: unlock, eal: disabled, domains: [{template: ALL}, {template: NO_ACCESS}]},
          {id: DMA1, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: DMAMUX1, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: PDM, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: LPUART11, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {
            id: LPUART12, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPSPI5, enabled: 'false',
            locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPSPI6, enabled: 'false', locked: unlock, eal: disabled,
            domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: LPI2C5, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: LPI2C6, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: CAN3,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: SAI4, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: RDC_SEMAPHORE1, enabled: 'false', locked: unlock, eal: disabled, domains: [
              {template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: MUA, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]},
          {id: MUB, enabled: 'true', locked: unlock, eal: disabled, domains: [{template: ALL}, {template: ALL}]}, {id: GPIO7, enabled: 'false', locked: unlock, eal: disabled,
            domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPIO8, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: GPIO9, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPIO10,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPIO11, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPIO12, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: RDC, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: KEY_MANAGER,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: ANADIG_MISC, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: PGMC_PPC0, enabled: 'false', locked: unlock, eal: disabled, domains: [{
                template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: SNVS, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]},
          {id: IOMUXC_SNVS, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: IOMUXC_SNVS_GPR, enabled: 'false',
            locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: SRAM, enabled: 'false', locked: unlock, eal: disabled, domains: [
              {template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: GPIO13, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]},
          {id: ROMCP, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: DCDC, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: OCOTP, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: PIT2, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: SSARC_HP,
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: SSARC_LP, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: CCM, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: CCM_OBS, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {
            id: SEMA4, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: RDC_SEMAPHORE2, enabled: 'false',
            locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: XRDC2_D1, enabled: 'false', locked: unlock, eal: disabled,
            domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: XRDC2_D0, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: GPU, base_region: {start: '0x00000000', size: '0x00100000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [
              {template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: CDOG, base_region: {start: '0x00000000', size: '0x00100000'}, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x00040000', size: '0x00010000'}, enabled: 'false',
            locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x00050000', size: '0x00010000'},
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x00060000',
              size: '0x00010000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {
              start: '0x00070000', size: '0x00010000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]},
          {id: AIPSTZ2, base_region: {start: '0x00080000', size: '0x00010000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x00090000', size: '0x00010000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [
              {template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x000A0000', size: '0x00010000'}, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x000B0000', size: '0x00010000'}, enabled: 'false',
            locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x000C0000', size: '0x00010000'},
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x000D0000',
              size: '0x00010000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {
              start: '0x000E0000', size: '0x00010000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]},
          {id: AIPSTZ2, base_region: {start: '0x000F0000', size: '0x00010000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x00100000', size: '0x00010000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [
              {template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x00110000', size: '0x00010000'}, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x00120000', size: '0x00010000'}, enabled: 'false',
            locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: AIPSTZ2, base_region: {start: '0x00130000', size: '0x00010000'},
            enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}]
    - mscs:
      - msc:
        - checker_id: 'MSC_XRDC'
        - slaves: [{id: SIM_DISP, base_region: {start: '0x00000000', size: '0x00100000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [{template: NO_ACCESS},
              {template: NO_ACCESS}]}, {id: SIM_M4, base_region: {start: '0x00000000', size: '0x00100000'}, enabled: 'false', locked: unlock, eal: disabled, domains: [
              {template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: SIM_M7, base_region: {start: '0x00000000', size: '0x00100000'}, enabled: 'false', locked: unlock,
            eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}, {id: ROMCP, base_region: {start: '0x00000000', size: '0x00040000'}, enabled: 'false',
            locked: unlock, eal: disabled, domains: [{template: NO_ACCESS}, {template: NO_ACCESS}]}]
    - mrcs:
      - mrc:
        - checker_id: 'MRC_XRDC'
        - slaves: [{id: SRAM_OC_cm4, base_region: {start: '0x00000000', size: '0x00040000'}, enabled: 'true', locked: unlock, eal: disabled, index: '0', domains: [
              {template: ALL}, {template: ALL}]}, {id: SRAM_OC_ECC1, base_region: {start: '0x00000000', size: '0x00010000'}, enabled: 'true', locked: unlock, eal: disabled,
            index: '0', domains: [{template: ALL}, {template: ALL}]}, {id: SRAM_OC_cm7, base_region: {start: '0x00000000', size: '0x00020000'}, enabled: 'true', locked: unlock,
            eal: disabled, index: '0', domains: [{template: ALL}, {template: NO_ACCESS}]}, {id: SRAM_OC_ECC2, base_region: {start: '0x00000000', size: '0x00010000'},
            enabled: 'true', locked: unlock, eal: disabled, index: '0', domains: [{template: ALL}, {template: ALL}]}, {id: CAAM, base_region: {start: '0x00000000',
              size: '0x00010000'}, enabled: 'true', locked: unlock, eal: disabled, index: '0', domains: [{template: ALL}, {template: ALL}]}, {id: SEMC, base_region: {
              start: '0x00000000', size: '0x04000000'}, enabled: 'true', locked: unlock, eal: disabled, index: '0', domains: [{template: ALL}, {template: ALL}]},
          {id: FLEXSPI1_REGION, base_region: {start: '0x00000000', size: '0x01000000'}, enabled: 'true', locked: unlock, eal: disabled, index: '0', domains: [{template: ALL},
              {template: ALL}]}, {id: FLEXSPI2_REGION, base_region: {start: '0x00000000', size: '0x02000000'}, enabled: 'false', locked: unlock, eal: disabled, index: '0',
            domains: [{template: ALL}, {template: ALL}]}]
  - masters:
    - master: {id: enet_1g_tx, domain_assignments: [{locked: 'false', domain_id: '0'}]}
    - master: {id: enet_1g_rx, domain_assignments: [{locked: 'false', domain_id: '0'}]}
    - master: {id: enet, domain_assignments: [{locked: 'false', domain_id: '0'}]}
    - master: {id: usdhc1, domain_assignments: [{locked: 'false', domain_id: '0'}]}
    - master: {id: usdhc2, domain_assignments: [{locked: 'false', domain_id: '0'}]}
    - master: {id: usb, domain_assignments: [{locked: 'false', domain_id: '0'}]}
    - master: {id: gc355, domain_assignments: [{locked: 'false', domain_id: '0'}]}
    - master: {id: pxp, domain_assignments: [{locked: 'false', domain_id: '0'}]}
    - master: {id: lcdif1, domain_assignments: [{locked: 'false', domain_id: '0'}]}
    - master: {id: csi, domain_assignments: [{locked: 'false', domain_id: '0'}]}
  - pdaps:
    - pdap:
      - checker_id: 'PDAP'
      - slaves: [{id: MECC1, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: MECC2, locked: 'false', semaphore_required: 'false',
          domains: [{template: rw}, {template: rw}]}, {id: XECC_FLEXSPI1, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]},
        {id: XECC_FLEXSPI2, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: XECC_SEMC, locked: 'false', semaphore_required: 'false',
          domains: [{template: rw}, {template: rw}]}, {id: FLEXRAM, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: EWM,
          locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: WDOG1, locked: 'false', semaphore_required: 'false', domains: [
            {template: rw}, {template: rw}]}, {id: WDOG2, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: RTWDOG3,
          locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: AOI2, locked: 'false', semaphore_required: 'false', domains: [
            {template: rw}, {template: rw}]}, {id: ADC_ETC, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: LPADC1,
          locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: LPADC2, locked: 'false', semaphore_required: 'false', domains: [
            {template: rw}, {template: rw}]}, {id: DAC, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: IEE_APC, locked: 'false',
          semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: DMAMUX0, locked: 'false', semaphore_required: 'false', domains: [{template: rw},
            {template: rw}]}, {id: LPUART1, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: LPUART2, locked: 'false',
          semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: LPUART3, locked: 'false', semaphore_required: 'false', domains: [{template: rw},
            {template: rw}]}, {id: LPUART4, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: LPUART5, locked: 'false',
          semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: LPUART6, locked: 'false', semaphore_required: 'false', domains: [{template: rw},
            {template: rw}]}, {id: LPUART7, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: LPUART8, locked: 'false',
          semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: LPUART9, locked: 'false', semaphore_required: 'false', domains: [{template: rw},
            {template: rw}]}, {id: LPUART10, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: FLEXIO1, locked: 'false',
          semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: FLEXIO2, locked: 'false', semaphore_required: 'false', domains: [{template: rw},
            {template: rw}]}, {id: CAN1, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: CAN2, locked: 'false', semaphore_required: 'false',
          domains: [{template: rw}, {template: rw}]}, {id: PIT1, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: KPP,
          locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: IOMUXC_GPR, locked: 'false', semaphore_required: 'false',
          domains: [{template: rw}, {template: rw}]}, {id: IOMUXC, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: GPT1,
          locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: GPT2, locked: 'false', semaphore_required: 'false', domains: [
            {template: rw}, {template: rw}]}, {id: GPT3, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: GPT4, locked: 'false',
          semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: GPT5, locked: 'false', semaphore_required: 'false', domains: [{template: rw},
            {template: rw}]}, {id: GPT6, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: LPI2C1, locked: 'false', semaphore_required: 'false',
          domains: [{template: rw}, {template: rw}]}, {id: LPI2C2, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: LPI2C3,
          locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: LPI2C4, locked: 'false', semaphore_required: 'false', domains: [
            {template: rw}, {template: rw}]}, {id: LPSPI1, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: LPSPI2,
          locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: LPSPI3, locked: 'false', semaphore_required: 'false', domains: [
            {template: rw}, {template: rw}]}, {id: LPSPI4, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: GPIO1, locked: 'false',
          semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: CCM_OBS, locked: 'false', semaphore_required: 'false', domains: [{template: rw},
            {template: rw}]}, {id: EMVSIM1, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: EMVSIM2, locked: 'false',
          semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: TMR1, locked: 'false', semaphore_required: 'false', domains: [{template: rw},
            {template: rw}]}, {id: TMR2, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: TMR3, locked: 'false', semaphore_required: 'false',
          domains: [{template: rw}, {template: rw}]}, {id: TMR4, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: ENC1,
          locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: ENC2, locked: 'false', semaphore_required: 'false', domains: [
            {template: rw}, {template: rw}]}, {id: ENC3, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: ENC4, locked: 'false',
          semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: PWM1, locked: 'false', semaphore_required: 'false', domains: [{template: rw},
            {template: rw}]}, {id: PWM2, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: PWM3, locked: 'false', semaphore_required: 'false',
          domains: [{template: rw}, {template: rw}]}, {id: PWM4, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: CMP1,
          locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: CMP2, locked: 'false', semaphore_required: 'false', domains: [
            {template: rw}, {template: rw}]}, {id: CMP3, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: CMP4, locked: 'false',
          semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: SPDIF, locked: 'false', semaphore_required: 'false', domains: [{template: rw},
            {template: rw}]}, {id: SAI1, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: SAI2, locked: 'false', semaphore_required: 'false',
          domains: [{template: rw}, {template: rw}]}, {id: SAI3, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: ASRC,
          locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: USDHC1, locked: 'false', semaphore_required: 'false', domains: [
            {template: rw}, {template: rw}]}, {id: USDHC2, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: ENET_1G,
          locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: ENET, locked: 'false', semaphore_required: 'false', domains: [
            {template: rw}, {template: rw}]}, {id: USBHSDCD1, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: USB_OTG2,
          locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: USB_OTG1, locked: 'false', semaphore_required: 'false', domains: [
            {template: rw}, {template: rw}]}, {id: CAAM, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: CSI, locked: 'false',
          semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: LCDIF, locked: 'false', semaphore_required: 'false', domains: [{template: rw},
            {template: rw}]}, {id: LCDIFV2, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: DSI_HOST, locked: 'false',
          semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: MIPI_CSI2RX, locked: 'false', semaphore_required: 'false', domains: [{template: rw},
            {template: rw}]}, {id: PXP, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: VIDEO_MUX, locked: 'false',
          semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: PGMC_PPC0, locked: 'false', semaphore_required: 'false', domains: [{template: rw},
            {template: rw}]}, {id: IOMUXC_LPSR, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: IOMUXC_LPSR_GPR, locked: 'false',
          semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: RTWDOG4, locked: 'false', semaphore_required: 'false', domains: [{template: rw},
            {template: rw}]}, {id: DMAMUX1, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: PDM, locked: 'false', semaphore_required: 'false',
          domains: [{template: rw}, {template: rw}]}, {id: LPUART11, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: LPUART12,
          locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: LPSPI5, locked: 'false', semaphore_required: 'false', domains: [
            {template: rw}, {template: rw}]}, {id: LPSPI6, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: LPI2C5,
          locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: LPI2C6, locked: 'false', semaphore_required: 'false', domains: [
            {template: rw}, {template: rw}]}, {id: CAN3, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: SAI4, locked: 'false',
          semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: XRDC2_D1, locked: 'false', semaphore_required: 'false', domains: [{template: rw},
            {template: rw}]}, {id: GPIO7, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: KEY_MANAGER, locked: 'false',
          semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: ANADIG_MISC, locked: 'false', semaphore_required: 'false', domains: [{template: rw},
            {template: rw}]}, {id: SNVS, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: IOMUXC_SNVS, locked: 'false',
          semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: IOMUXC_SNVS_GPR, locked: 'false', semaphore_required: 'false', domains: [
            {template: rw}, {template: rw}]}, {id: SRAM, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: GPIO13, locked: 'false',
          semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: ROMCP, locked: 'false', semaphore_required: 'false', domains: [{template: rw},
            {template: rw}]}, {id: DCDC, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: OCOTP, locked: 'false', semaphore_required: 'false',
          domains: [{template: rw}, {template: rw}]}, {id: PIT2, locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: SSARC_HP,
          locked: 'false', semaphore_required: 'false', domains: [{template: rw}, {template: rw}]}, {id: CCM, locked: 'false', semaphore_required: 'false', domains: [
            {template: rw}, {template: rw}]}, {id: AIPSTZ2, base_region: {start: '0x00050000', size: '0x00010000'}, locked: 'false', semaphore_required: 'false',
          domains: [{template: rw}, {template: rw}]}, {id: AIPSTZ2, base_region: {start: '0x00060000', size: '0x00010000'}, locked: 'false', semaphore_required: 'false',
          domains: [{template: rw}, {template: rw}]}, {id: AIPSTZ2, base_region: {start: '0x00070000', size: '0x00010000'}, locked: 'false', semaphore_required: 'false',
          domains: [{template: rw}, {template: rw}]}, {id: AIPSTZ2, base_region: {start: '0x00080000', size: '0x00010000'}, locked: 'false', semaphore_required: 'false',
          domains: [{template: rw}, {template: rw}]}, {id: AIPSTZ2, base_region: {start: '0x000A0000', size: '0x00010000'}, locked: 'false', semaphore_required: 'false',
          domains: [{template: rw}, {template: rw}]}, {id: AIPSTZ2, base_region: {start: '0x000C0000', size: '0x00010000'}, locked: 'false', semaphore_required: 'false',
          domains: [{template: rw}, {template: rw}]}]
  - mrcs:
    - mrc:
      - checker_id: 'MRC_RDC'
      - slaves: [{id: SRAM_OC_cm4, base_region: {start: '0x00000000', size: '0x00000080'}, enabled: 'false', locked: 'false', index: '0', domains: [{template: rw},
            {template: rw}]}, {id: SIM_DISP, base_region: {start: '0x00000000', size: '0x00100000'}, enabled: 'false', locked: 'false', index: '0', domains: [{template: rw},
            {template: rw}]}, {id: SRAM_OC_cm7, base_region: {start: '0x00000000', size: '0x00000080'}, enabled: 'false', locked: 'false', index: '0', domains: [
            {template: rw}, {template: rw}]}, {id: SIM_M4, base_region: {start: '0x00000000', size: '0x00100000'}, enabled: 'false', locked: 'false', index: '0',
          domains: [{template: rw}, {template: rw}]}, {id: CAAM, base_region: {start: '0x00000000', size: '0x00002000'}, enabled: 'false', locked: 'false', index: '0',
          domains: [{template: rw}, {template: rw}]}, {id: SIM_M7, base_region: {start: '0x00000000', size: '0x00100000'}, enabled: 'false', locked: 'false', index: '0',
          domains: [{template: rw}, {template: rw}]}, {id: SRAM_OC1, base_region: {start: '0x00000000', size: '0x00000080'}, enabled: 'false', locked: 'false', index: '0',
          domains: [{template: rw}, {template: rw}]}, {id: SRAM_OC2, base_region: {start: '0x00000000', size: '0x00000080'}, enabled: 'false', locked: 'false', index: '0',
          domains: [{template: rw}, {template: rw}]}, {id: SEMC, base_region: {start: '0x00000000', size: '0x00001000'}, enabled: 'false', locked: 'false', index: '0',
          domains: [{template: rw}, {template: rw}]}, {id: FLEXSPI1_REGION, base_region: {start: '0x00000000', size: '0x00001000'}, enabled: 'false', locked: 'false',
          index: '0', domains: [{template: rw}, {template: rw}]}, {id: FLEXSPI2_REGION, base_region: {start: '0x00000000', size: '0x00001000'}, enabled: 'false',
          locked: 'false', index: '0', domains: [{template: rw}, {template: rw}]}]
- global_options:
  - 0:
    - id: [XRDC2_D0_MCR_GCL, XRDC2_D1_MCR_GCL]
  - yes:
    - id: [XRDC2_D0_MCR_GVLDC, XRDC2_D0_MCR_GVLDM, XRDC2_D1_MCR_GVLDC, XRDC2_D1_MCR_GVLDM]
- user_memory_regions: []
- apus:
  - apu:
    - enabled: 'false'
    - id: 'apc'
    - regions: [{encrypt_enabled: 'false', index: '0', locked: 'false', start: '0x00000000', size: '0x00000008'}, {encrypt_enabled: 'false', index: '1', locked: 'false',
        start: '0x00000000', size: '0x00000008'}, {encrypt_enabled: 'false', index: '2', locked: 'false', start: '0x00000000', size: '0x00000008'}, {encrypt_enabled: 'false',
        index: '3', locked: 'false', start: '0x00000000', size: '0x00000008'}, {encrypt_enabled: 'false', index: '4', locked: 'false', start: '0x00000000', size: '0x00000008'},
      {encrypt_enabled: 'false', index: '5', locked: 'false', start: '0x00000000', size: '0x00000008'}, {encrypt_enabled: 'false', index: '6', locked: 'false', start: '0x00000000',
        size: '0x00000008'}, {encrypt_enabled: 'false', index: '7', locked: 'false', start: '0x00000000', size: '0x00000008'}]
- mpus:
  - mpu:
    - enabled: 'true'
    - masters: 'cm4_ahbc cm4_ahbs'
    - priv_default_map: 'true'
    - handler_enabled: 'false'
    - generate_code_for_disabled_regions: 'false'
    - attributes: [{index: '0', id: '0', memory_type: normal, regions_properties: [{id: inner, cacheable: 'false', write_back: 'false', write_allocation: 'false'},
          {id: outer, cacheable: 'false', write_back: 'false', write_allocation: 'false'}]}, {index: '1', id: '1', memory_type: device, regions_properties: [{id: inner,
            cacheable: 'false', write_back: 'false', write_allocation: 'false'}, {id: outer, cacheable: 'false', write_back: 'false', write_allocation: 'false'}]},
      {index: '2', id: '2', memory_type: device, regions_properties: [{id: inner, cacheable: 'false', write_back: 'false', write_allocation: 'false'}, {id: outer,
            cacheable: 'false', write_back: 'false', write_allocation: 'false'}]}, {index: '3', id: '3', memory_type: device, regions_properties: [{id: inner, cacheable: 'false',
            write_back: 'false', write_allocation: 'false'}, {id: outer, cacheable: 'false', write_back: 'false', write_allocation: 'false'}]}, {index: '4', id: '4',
        memory_type: device, regions_properties: [{id: inner, cacheable: 'false', write_back: 'false', write_allocation: 'false'}, {id: outer, cacheable: 'false',
            write_back: 'false', write_allocation: 'false'}]}, {index: '5', id: '5', memory_type: device, regions_properties: [{id: inner, cacheable: 'false', write_back: 'false',
            write_allocation: 'false'}, {id: outer, cacheable: 'false', write_back: 'false', write_allocation: 'false'}]}, {index: '6', id: '6', memory_type: device,
        regions_properties: [{id: inner, cacheable: 'false', write_back: 'false', write_allocation: 'false'}, {id: outer, cacheable: 'false', write_back: 'false',
            write_allocation: 'false'}]}, {index: '7', id: '7', memory_type: device, regions_properties: [{id: inner, cacheable: 'false', write_back: 'false', write_allocation: 'false'},
          {id: outer, cacheable: 'false', write_back: 'false', write_allocation: 'false'}]}]
    - regions: [{executable: 'false', read_only: 'false', shareability: non_shareable, srd: '0', attributes_index: '0', index: '0', enabled: 'true', security: user,
        start: '0x20360000', size: '0x00020000'}, {executable: 'false', read_only: 'false', shareability: non_shareable, srd: '0', attributes_index: '1', index: '1',
        enabled: 'false', security: priv, start: '0x00000000', size: '0x00000020'}, {executable: 'false', read_only: 'false', shareability: non_shareable, srd: '0',
        attributes_index: '2', index: '2', enabled: 'false', security: priv, start: '0x00000000', size: '0x00000020'}, {executable: 'false', read_only: 'false', shareability: non_shareable,
        srd: '0', attributes_index: '3', index: '3', enabled: 'false', security: priv, start: '0x00000000', size: '0x00000020'}, {executable: 'false', read_only: 'false',
        shareability: non_shareable, srd: '0', attributes_index: '4', index: '4', enabled: 'false', security: priv, start: '0x00000000', size: '0x00000020'}, {executable: 'false',
        read_only: 'false', shareability: non_shareable, srd: '0', attributes_index: '5', index: '5', enabled: 'false', security: priv, start: '0x00000000', size: '0x00000020'},
      {executable: 'false', read_only: 'false', shareability: non_shareable, srd: '0', attributes_index: '6', index: '6', enabled: 'false', security: priv, start: '0x00000000',
        size: '0x00000020'}, {executable: 'false', read_only: 'false', shareability: non_shareable, srd: '0', attributes_index: '7', index: '7', enabled: 'false',
        security: priv, start: '0x00000000', size: '0x00000020'}]
  - mpu:
    - enabled: 'true'
    - masters: 'cm7_ahb cm7_axi'
    - priv_default_map: 'true'
    - handler_enabled: 'false'
    - generate_code_for_disabled_regions: 'false'
    - attributes: [{index: '0', id: '0', memory_type: strongly_ordered, regions_properties: [{id: inner, cacheable: 'false', write_back: 'false', write_allocation: 'false'},
          {id: outer, cacheable: 'false', write_back: 'false', write_allocation: 'false'}]}, {index: '1', id: '1', memory_type: device, regions_properties: [{id: inner,
            cacheable: 'false', write_back: 'false', write_allocation: 'false'}, {id: outer, cacheable: 'false', write_back: 'false', write_allocation: 'false'}]},
      {index: '2', id: '2', memory_type: device, regions_properties: [{id: inner, cacheable: 'false', write_back: 'false', write_allocation: 'false'}, {id: outer,
            cacheable: 'false', write_back: 'false', write_allocation: 'false'}]}, {index: '3', id: '3', memory_type: device, regions_properties: [{id: inner, cacheable: 'false',
            write_back: 'false', write_allocation: 'false'}, {id: outer, cacheable: 'false', write_back: 'false', write_allocation: 'false'}]}, {index: '4', id: '4',
        memory_type: normal, regions_properties: [{id: inner, cacheable: 'true', write_back: 'true', write_allocation: 'false'}, {id: outer, cacheable: 'true', write_back: 'true',
            write_allocation: 'false'}]}, {index: '5', id: '5', memory_type: normal, regions_properties: [{id: inner, cacheable: 'true', write_back: 'true', write_allocation: 'false'},
          {id: outer, cacheable: 'true', write_back: 'true', write_allocation: 'false'}]}, {index: '6', id: '6', memory_type: normal, regions_properties: [{id: inner,
            cacheable: 'true', write_back: 'true', write_allocation: 'false'}, {id: outer, cacheable: 'true', write_back: 'true', write_allocation: 'false'}]}, {
        index: '7', id: '7', memory_type: normal, regions_properties: [{id: inner, cacheable: 'true', write_back: 'true', write_allocation: 'false'}, {id: outer,
            cacheable: 'true', write_back: 'true', write_allocation: 'false'}]}, {index: '8', id: '8', memory_type: normal, regions_properties: [{id: inner, cacheable: 'true',
            write_back: 'true', write_allocation: 'false'}, {id: outer, cacheable: 'true', write_back: 'true', write_allocation: 'false'}]}, {index: '9', id: '9',
        memory_type: normal, regions_properties: [{id: inner, cacheable: 'true', write_back: 'true', write_allocation: 'false'}, {id: outer, cacheable: 'true', write_back: 'true',
            write_allocation: 'false'}]}, {index: '10', id: '10', memory_type: normal, regions_properties: [{id: inner, cacheable: 'false', write_back: 'false', write_allocation: 'false'},
          {id: outer, cacheable: 'false', write_back: 'false', write_allocation: 'false'}]}, {index: '11', id: '11', memory_type: device, regions_properties: [{id: inner,
            cacheable: 'false', write_back: 'false', write_allocation: 'false'}, {id: outer, cacheable: 'false', write_back: 'false', write_allocation: 'false'}]},
      {index: '12', id: '12', memory_type: device, regions_properties: [{id: inner, cacheable: 'false', write_back: 'false', write_allocation: 'false'}, {id: outer,
            cacheable: 'false', write_back: 'false', write_allocation: 'false'}]}, {index: '13', id: '13', memory_type: device, regions_properties: [{id: inner, cacheable: 'false',
            write_back: 'false', write_allocation: 'false'}, {id: outer, cacheable: 'false', write_back: 'false', write_allocation: 'false'}]}, {index: '14', id: '14',
        memory_type: device, regions_properties: [{id: inner, cacheable: 'false', write_back: 'false', write_allocation: 'false'}, {id: outer, cacheable: 'false',
            write_back: 'false', write_allocation: 'false'}]}, {index: '15', id: '15', memory_type: device, regions_properties: [{id: inner, cacheable: 'false', write_back: 'false',
            write_allocation: 'false'}, {id: outer, cacheable: 'false', write_back: 'false', write_allocation: 'false'}]}]
    - regions: [{executable: 'false', read_only: no_access, shareability: shareable, srd: '0', attributes_index: '0', index: '0', enabled: 'true', security: priv,
        start: '0x00000000', size: '0x100000000'}, {executable: 'true', read_only: 'false', shareability: non_shareable, srd: '0', attributes_index: '1', index: '1',
        enabled: 'true', security: user, start: '0x80000000', size: '0x20000000'}, {executable: 'true', read_only: 'false', shareability: non_shareable, srd: '0',
        attributes_index: '2', index: '2', enabled: 'true', security: user, start: '0x60000000', size: '0x20000000'}, {executable: 'true', read_only: 'false', shareability: non_shareable,
        srd: '0', attributes_index: '3', index: '3', enabled: 'true', security: user, start: '0x00000000', size: '0x40000000'}, {executable: 'true', read_only: 'false',
        shareability: non_shareable, srd: '0', attributes_index: '4', index: '4', enabled: 'true', security: user, start: '0x00000000', size: '0x00040000'}, {executable: 'true',
        read_only: 'false', shareability: non_shareable, srd: '0', attributes_index: '5', index: '5', enabled: 'true', security: user, start: '0x20000000', size: '0x00040000'},
      {executable: 'true', read_only: 'false', shareability: non_shareable, srd: '0', attributes_index: '6', index: '6', enabled: 'true', security: user, start: '0x20200000',
        size: '0x00100000'}, {executable: 'true', read_only: 'false', shareability: non_shareable, srd: '0', attributes_index: '7', index: '7', enabled: 'true', security: user,
        start: '0x20300000', size: '0x00080000'}, {executable: 'true', read_only: 'true', shareability: non_shareable, srd: '0', attributes_index: '8', index: '8',
        enabled: 'true', security: user, start: '0x00000000', size: '0x01000000'}, {executable: 'true', read_only: 'false', shareability: non_shareable, srd: '0',
        attributes_index: '9', index: '9', enabled: 'true', security: user, start: '0x80000000', size: '0x04000000'}, {executable: 'false', read_only: 'false', shareability: non_shareable,
        srd: '0', attributes_index: '10', index: '10', enabled: 'true', security: user, start: '0x20360000', size: '0x00020000'}, {executable: 'false', read_only: 'false',
        shareability: non_shareable, srd: '0', attributes_index: '11', index: '11', enabled: 'true', security: user, start: '0x40000000', size: '0x01000000'}, {executable: 'false',
        read_only: 'false', shareability: non_shareable, srd: '0', attributes_index: '12', index: '12', enabled: 'true', security: user, start: '0x41000000', size: '0x00200000'},
      {executable: 'false', read_only: 'false', shareability: non_shareable, srd: '0', attributes_index: '13', index: '13', enabled: 'true', security: user, start: '0x41400000',
        size: '0x00100000'}, {executable: 'false', read_only: 'false', shareability: non_shareable, srd: '0', attributes_index: '14', index: '14', enabled: 'true',
        security: user, start: '0x41800000', size: '0x00200000'}, {executable: 'false', read_only: 'false', shareability: non_shareable, srd: '0', attributes_index: '15',
        index: '15', enabled: 'true', security: user, start: '0x42000000', size: '0x00100000'}]
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitTEE
 * Description   :
 *
 * END ****************************************************************************************************************/

/***********************************************************************************************************************
 * BOARD_InitMPU function
 **********************************************************************************************************************/
void BOARD_InitMPU()
{
    /* MPU ARM v7 configuration */

#if defined(__ICACHE_PRESENT) && __ICACHE_PRESENT
    /* Disable I cache and D cache */
    if (SCB_CCR_IC_Msk == (SCB_CCR_IC_Msk & SCB->CCR))
    {
        SCB_DisableICache();
    }
#endif
#if defined(__DCACHE_PRESENT) && __DCACHE_PRESENT
    if (SCB_CCR_DC_Msk == (SCB_CCR_DC_Msk & SCB->CCR))
    {
        SCB_DisableDCache();
    }
#endif

    /* Disable MPU */
    ARM_MPU_Disable();

    /* Set MPU region 0 */
    MPU->RBAR = (MPU_REGION_0_BASE & MPU_RBAR_ADDR_Msk) | ((0U << MPU_RBAR_REGION_Pos) & MPU_RBAR_REGION_Msk) |
                ((1U << MPU_RBAR_VALID_Pos) & MPU_RBAR_VALID_Msk);
    MPU->RASR = ((1U << MPU_RASR_XN_Pos) & MPU_RASR_XN_Msk) | ((3U << MPU_RASR_AP_Pos) & MPU_RASR_AP_Msk) |
                ((1U << MPU_RASR_TEX_Pos) & MPU_RASR_TEX_Msk) | ((0U << MPU_RASR_S_Pos) & MPU_RASR_S_Msk) |
                ((0U << MPU_RASR_C_Pos) & MPU_RASR_C_Msk) | ((0U << MPU_RASR_B_Pos) & MPU_RASR_B_Msk) |
                ((0U << MPU_RASR_SRD_Pos) & MPU_RASR_SRD_Msk) | ((16U << MPU_RASR_SIZE_Pos) & MPU_RASR_SIZE_Msk) |
                ((1U << MPU_RASR_ENABLE_Pos) & MPU_RASR_ENABLE_Msk);

    /* Enable MPU */
    ARM_MPU_Enable(((1U << MPU_CTRL_PRIVDEFENA_Pos) & MPU_CTRL_PRIVDEFENA_Msk) |
                   ((0U << MPU_CTRL_HFNMIENA_Pos) & MPU_CTRL_HFNMIENA_Msk));

    /* Enable I cache and D cache */
#if defined(__DCACHE_PRESENT) && __DCACHE_PRESENT
    SCB_EnableDCache();
#endif
#if defined(__ICACHE_PRESENT) && __ICACHE_PRESENT
    SCB_EnableICache();
#endif
}

/***********************************************************************************************************************
 * BOARD_InitTEE function
 **********************************************************************************************************************/
void BOARD_InitTEE()
{
    BOARD_InitMPU();
}

/***********************************************************************************************************************
 * BOARD_InitBootTEE function
 **********************************************************************************************************************/
void BOARD_InitBootTEE()
{
    BOARD_InitTEE();
}
