# config to select component, the format is CONFIG_USE_${component}
set(CONFIG_USE_middleware_multicore_rpmsg_lite_freertos true)
set(CONFIG_USE_component_wm8904_adapter true)
set(CONFIG_USE_component_i3c_adapter true)
set(CONFIG_USE_middleware_usb_device_ip3511hs_MIMXRT685S_cm33 true)
set(CONFIG_USE_component_serial_manager_uart true)
set(CONFIG_USE_driver_flexcomm_usart true)
set(CONFIG_USE_middleware_freertos-kernel_MIMXRT685S_cm33 true)
set(MCUX_DEVICE "MIMXRT685S_cm33")