/*
 * Copyright 2019-2022 NXP
 * All rights reserved.
 *
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __CONFIG_NN_H__
#define __CONFIG_NN_H__

#define NN_ENABLE_xa_nn_malloc                                 1
#define NN_ENABLE_xa_nn_free                                   1
#define NN_ENABLE_xa_nn_matXvec_16x16_16                       1
#define NN_ENABLE_xa_nn_matXvec_16x16_32                       1
#define NN_ENABLE_xa_nn_matXvec_16x16_64                       1
#define NN_ENABLE_xa_nn_matXvec_16x16_16_tanh                  1
#define NN_ENABLE_xa_nn_matXvec_16x16_16_sigmoid               1
#define NN_ENABLE_xa_nn_matXvec_batch_16x16_64                 1
#define NN_ENABLE_xa_nn_matmul_16x16_16                        1
#define NN_ENABLE_xa_nn_matXvec_8x16_16                        1
#define NN_ENABLE_xa_nn_matXvec_8x16_32                        1
#define NN_ENABLE_xa_nn_matXvec_8x16_64                        1
#define NN_ENABLE_xa_nn_matXvec_8x16_16_tanh                   1
#define NN_ENABLE_xa_nn_matXvec_8x16_16_sigmoid                1
#define NN_ENABLE_xa_nn_matXvec_batch_8x16_64                  1
#define NN_ENABLE_xa_nn_matmul_8x16_16                         1
#define NN_ENABLE_xa_nn_matXvec_8x8_8                          1
#define NN_ENABLE_xa_nn_matXvec_8x8_16                         1
#define NN_ENABLE_xa_nn_matXvec_8x8_32                         1
#define NN_ENABLE_xa_nn_matXvec_8x8_8_tanh                     1
#define NN_ENABLE_xa_nn_matXvec_8x8_8_sigmoid                  1
#define NN_ENABLE_xa_nn_matXvec_batch_8x8_32                   1
#define NN_ENABLE_xa_nn_matmul_8x8_8                           1
#define NN_ENABLE_xa_nn_matXvec_f32xf32_f32_sigmoid            1
#define NN_ENABLE_xa_nn_matXvec_f32xf32_f32_tanh               1
#define NN_ENABLE_xa_nn_matXvec_f32xf32_f32                    1
#define NN_ENABLE_xa_nn_matXvec_batch_f32xf32_f32              1
#define NN_ENABLE_xa_nn_matmul_f32xf32_f32                     1
#define NN_ENABLE_xa_nn_matXvec_asym8uxasym8u_asym8u           1
#define NN_ENABLE_xa_nn_matXvec_sym8sxasym8s_asym8s            1
#define NN_ENABLE_xa_nn_matXvec_out_stride_sym8sxasym8s_16     1
#define NN_ENABLE_xa_nn_vec_sigmoid_32_32                      1
#define NN_ENABLE_xa_nn_vec_tanh_32_32                         1
#define NN_ENABLE_xa_nn_vec_relu_std_32_32                     1
#define NN_ENABLE_xa_nn_vec_relu_32_32                         1
#define NN_ENABLE_xa_nn_vec_relu1_32_32                        1
#define NN_ENABLE_xa_nn_vec_relu6_32_32                        1
#define NN_ENABLE_xa_nn_vec_softmax_32_32                      1
#define NN_ENABLE_xa_nn_vec_sigmoid_f32_f32                    1
#define NN_ENABLE_xa_nn_vec_tanh_f32_f32                       1
#define NN_ENABLE_xa_nn_vec_relu_f32_f32                       1
#define NN_ENABLE_xa_nn_vec_relu_std_f32_f32                   1
#define NN_ENABLE_xa_nn_vec_relu1_f32_f32                      1
#define NN_ENABLE_xa_nn_vec_relu6_f32_f32                      1
#define NN_ENABLE_xa_nn_vec_softmax_f32_f32                    1
#define NN_ENABLE_xa_nn_vec_sigmoid_32_16                      1
#define NN_ENABLE_xa_nn_vec_tanh_32_16                         1
#define NN_ENABLE_xa_nn_vec_sigmoid_32_8                       1
#define NN_ENABLE_xa_nn_vec_tanh_32_8                          1
#define NN_ENABLE_xa_nn_vec_relu_16_16                         1
#define NN_ENABLE_xa_nn_vec_relu_std_16_16                     1
#define NN_ENABLE_xa_nn_vec_relu_8_8                           1
#define NN_ENABLE_xa_nn_vec_relu_std_8_8                       1
#define NN_ENABLE_xa_nn_vec_interpolation_q15                  1
#define NN_ENABLE_xa_nn_conv1d_std_getsize                     1
#define NN_ENABLE_xa_nn_conv1d_std_8x16                        1
#define NN_ENABLE_xa_nn_conv1d_std_8x8                         1
#define NN_ENABLE_xa_nn_conv1d_std_16x16                       1
#define NN_ENABLE_xa_nn_conv1d_std_f32                         1
#define NN_ENABLE_xa_nn_conv2d_std_getsize                     1
#define NN_ENABLE_xa_nn_conv2d_std_8x16                        1
#define NN_ENABLE_xa_nn_conv2d_std_8x8                         1
#define NN_ENABLE_xa_nn_conv2d_std_16x16                       1
#define NN_ENABLE_xa_nn_conv2d_std_f32                         1
#define NN_ENABLE_xa_nn_conv2d_pointwise_f32                   1
#define NN_ENABLE_xa_nn_conv2d_pointwise_8x16                  1
#define NN_ENABLE_xa_nn_conv2d_pointwise_8x8                   1
#define NN_ENABLE_xa_nn_conv2d_depthwise_getsize               1
#define NN_ENABLE_xa_nn_conv2d_depthwise_8x8                   1
#define NN_ENABLE_xa_nn_conv2d_depthwise_f32                   1
#define NN_ENABLE_xa_nn_conv2d_depthwise_8x16                  1
#define NN_ENABLE_xa_nn_conv2d_depthwise_16x16                 1
#define NN_ENABLE_xa_nn_conv2d_pointwise_16x16                 1
#define NN_ENABLE_xa_nn_avgpool_8                              1
#define NN_ENABLE_xa_nn_avgpool_16                             1
#define NN_ENABLE_xa_nn_avgpool_f32                            1
#define NN_ENABLE_xa_nn_avgpool_asym8u                         1
#define NN_ENABLE_xa_nn_avgpool_getsize                        1
#define NN_ENABLE_xa_nn_maxpool_8                              1
#define NN_ENABLE_xa_nn_maxpool_16                             1
#define NN_ENABLE_xa_nn_maxpool_f32                            1
#define NN_ENABLE_xa_nn_maxpool_asym8u                         1
#define NN_ENABLE_xa_nn_maxpool_getsize                        1
#define NN_ENABLE_xa_nn_fully_connected_f32                    1
#define NN_ENABLE_xa_nn_fully_connected_16x16_16               1
#define NN_ENABLE_xa_nn_fully_connected_8x16_16                1
#define NN_ENABLE_xa_nn_fully_connected_8x8_8                  1
#define NN_ENABLE_xa_nn_fully_connected_asym8uxasym8u_asym8u   1
#define NN_ENABLE_xa_nn_fully_connected_sym8sxasym8s_asym8s    1
#define NN_ENABLE_xa_nn_vec_activation_min_max_asym8u_asym8u   1
#define NN_ENABLE_xa_nn_vec_activation_min_max_f32_f32         1
#define NN_ENABLE_xa_nn_vec_softmax_asym8u_asym8u              1
#define NN_ENABLE_xa_nn_vec_softmax_asym8s_asym8s              1
#define NN_ENABLE_xa_nn_vec_softmax_asym8s_16                  1
#define NN_ENABLE_xa_nn_vec_sigmoid_asym8u_asym8u              1
#define NN_ENABLE_xa_nn_vec_sigmoid_asym8s_asym8s              1
#define NN_ENABLE_get_softmax_scratch_size                     1
#define NN_ENABLE_xa_nn_vec_activation_min_max_8_8             1
#define NN_ENABLE_xa_nn_vec_activation_min_max_16_16           1
#define NN_ENABLE_xa_nn_vec_relu_asym8u_asym8u                 1
#define NN_ENABLE_xa_nn_vec_relu_asym8s_asym8s                 1
#define NN_ENABLE_xa_nn_vec_prelu_asym8s_asym8s                1
#define NN_ENABLE_xa_nn_vec_hard_swish_asym8s_asym8s           1
#define NN_ENABLE_xa_nn_vec_tanh_asym8s_asym8s                 1
#define NN_ENABLE_xa_nn_conv1d_std_asym8uxasym8u               1
#define NN_ENABLE_xa_nn_conv2d_std_asym8uxasym8u               1
#define NN_ENABLE_xa_nn_conv2d_std_per_chan_sym8sxasym8s       1
#define NN_ENABLE_xa_nn_matXvec_batch_asym8uxasym8u_asym8u     1
#define NN_ENABLE_xa_nn_matmul_asym8uxasym8u_asym8u            1
#define NN_ENABLE_xa_nn_matmul_per_chan_sym8sxasym8s_asym8s    1
#define NN_ENABLE_xa_nn_conv2d_depthwise_asym8uxasym8u         1
#define NN_ENABLE_xa_nn_conv2d_pointwise_asym8uxasym8u         1
#define NN_ENABLE_xa_nn_conv2d_depthwise_per_chan_sym8sxasym8s 1
#define NN_ENABLE_xa_nn_conv2d_pointwise_per_chan_sym8sxasym8s 1
#define NN_ENABLE_xa_nn_elm_mul_f32xf32_f32                    1
#define NN_ENABLE_xa_nn_elm_add_f32xf32_f32                    1
#define NN_ENABLE_xa_nn_elm_mul_acc_f32xf32_f32                1
#define NN_ENABLE_xa_nn_elm_sub_f32xf32_f32                    1
#define NN_ENABLE_xa_nn_elm_div_f32xf32_f32                    1
#define NN_ENABLE_xa_nn_elm_floor_f32_f32                      1
#define NN_ENABLE_xa_nn_elm_add_asym8uxasym8u_asym8u           1
#define NN_ENABLE_xa_nn_elm_add_asym8sxasym8s_asym8s           1
#define NN_ENABLE_xa_nn_elm_sub_asym8uxasym8u_asym8u           1
#define NN_ENABLE_xa_nn_elm_sub_asym8sxasym8s_asym8s           1
#define NN_ENABLE_xa_nn_elm_mul_asym8uxasym8u_asym8u           1
#define NN_ENABLE_xa_nn_elm_mul_asym8sxasym8s_asym8s           1
#define NN_ENABLE_xa_nn_elm_quantize_asym16s_asym8s            0
#define NN_ENABLE_xa_nn_elm_max_8x8_8                          1
#define NN_ENABLE_xa_nn_elm_min_8x8_8                          1
#define NN_ENABLE_xa_nn_elm_equal_asym8sxasym8s                1
#define NN_ENABLE_xa_nn_elm_notequal_asym8sxasym8s             1
#define NN_ENABLE_xa_nn_elm_greater_asym8sxasym8s              1
#define NN_ENABLE_xa_nn_elm_greaterequal_asym8sxasym8s         1
#define NN_ENABLE_xa_nn_elm_less_asym8sxasym8s                 1
#define NN_ENABLE_xa_nn_elm_lessequal_asym8sxasym8s            1
#define NN_ENABLE_xa_nn_reduce_max_getsize_nhwc                0
#define NN_ENABLE_xa_nn_reduce_max_4D_asym8s_asym8s            1
#define NN_ENABLE_xa_nn_elm_logicaland_boolxbool_bool          1
#define NN_ENABLE_xa_nn_elm_logicalor_boolxbool_bool           1
#define NN_ENABLE_xa_nn_elm_logicalnot_bool_bool               1
#define NN_ENABLE_xa_nn_l2_norm_f32                            1
#define NN_ENABLE_xa_nn_l2_norm_asym8s_asym8s                  1
#define NN_ENABLE_xa_nn_dot_prod_f32xf32_f32                   1
#define NN_ENABLE_xa_nn_dot_prod_16x16_asym8s                  1

#endif // __CONFIG_NN_H__
