# config to select component, the format is CONFIG_USE_${component}
# Please refer to cmake files below to get available components:
#  ${SdkRootDirPath}/devices/MK22F51212/all_lib_device.cmake

set(CONFIG_COMPILER gcc)
set(CONFIG_TOOLCHAIN armgcc)
set(CONFIG_USE_COMPONENT_CONFIGURATION false)
set(CONFIG_USE_utility_debug_console_lite true)
set(CONFIG_USE_utility_assert_lite true)
set(CONFIG_USE_driver_port true)
set(CONFIG_USE_driver_i2c true)
set(CONFIG_USE_driver_fxos8700cq true)
set(CONFIG_USE_driver_gpio true)
set(CONFIG_USE_driver_clock true)
set(CONFIG_USE_driver_common true)
set(CONFIG_USE_device_MK22F51212_CMSIS true)
set(CONFIG_USE_component_uart_adapter true)
set(CONFIG_USE_driver_uart true)
set(CONFIG_USE_component_lists true)
set(CONFIG_USE_device_MK22F51212_startup true)
set(CONFIG_USE_driver_lpuart true)
set(CONFIG_USE_driver_smc true)
set(CONFIG_USE_utilities_misc_utilities true)
set(CONFIG_USE_utility_str true)
set(CONFIG_USE_CMSIS_Include_core_cm true)
set(CONFIG_USE_device_MK22F51212_system true)
set(CONFIG_CORE cm4f)
set(CONFIG_DEVICE MK22F51212)
set(CONFIG_BOARD frdmk22f)
set(CONFIG_KIT frdmk22f)
set(CONFIG_DEVICE_ID MK22FN512xxx12)
set(CONFIG_FPU SP_FPU)
set(CONFIG_DSP NO_DSP)
