PRIMARY_SERVICE(service_gatt, gBleSig_GenericAttributeProfile_d)
        CHARACTERISTIC(char_service_changed, gBleSig_GattServiceChanged_d, (gGattCharPropIndicate_c) )
            VALUE(value_service_changed, gBleSig_GattServiceChanged_d, (gPermissionNone_c), 4, 0x00, 0x00, 0x00, 0x00)
            CCCD(cccd_service_changed)

PRIMARY_SERVICE(service_gap, gBleSig_GenericAccessProfile_d)
    CHARACTERISTIC(char_device_name, gBleSig_GapDeviceName_d, (gGattCharPropRead_c |gGattCharPropWrite_c ) )
            VALUE(value_device_name, gBleSig_GapDeviceName_d, (gPermissionFlagReadable_c | gPermissionFlagWritable_c), 11, "NXP_BLE_CPS")
    CHARACTERISTIC(char_appearance, gBleSig_GapAppearance_d, (gGattCharPropRead_c) )
            VALUE(value_appearance, gBleSig_GapAppearance_d, (gPermissionFlagReadable_c), 2, UuidArray(gCyclingPowerSensor_c))
    CHARACTERISTIC(char_ppcp, gBleSig_GapPpcp_d, (gGattCharPropRead_c) )
            VALUE(value_ppcp, gBleSig_GapPpcp_d, (gPermissionFlagReadable_c), 8, 0x0A, 0x00, 0x10, 0x00, 0x64, 0x00, 0xE2, 0x04)

PRIMARY_SERVICE(service_cp, gBleSig_CyclingPowerService_d)
    CHARACTERISTIC(char_cp_feature, gBleSig_CpFeature_d, (gGattCharPropRead_c))
        VALUE(value_cp_feature, gBleSig_CpFeature_d, (gPermissionFlagReadable_c), 4, 0x00, 0x00, 0x00, 0x00)
    CHARACTERISTIC(char_cp_measurement, gBleSig_CpMeasurement_d, (gGattCharPropNotify_c | gGattCharPropBroadcast_c))
        VALUE_VARLEN(value_cp_measurement, gBleSig_CpMeasurement_d, (gPermissionNone_c), 23, 1, 0x00)
        DESCRIPTOR(desc_cp_meas, gBleSig_SCCD_d, (gPermissionFlagReadable_c | gPermissionFlagWritable_c), 2, 0x00, 0x00)
        CCCD(cccd_cp_measurement)
    CHARACTERISTIC(char_sensor_location, gBleSig_SensorLocation_d, (gGattCharPropRead_c))
        VALUE(value_sensor_location, gBleSig_SensorLocation_d, (gPermissionFlagReadable_c), 1, 0x00)
    CHARACTERISTIC(char_cp_ctrl_point, gBleSig_CpControlPoint_d, (gGattCharPropIndicate_c | gGattCharPropWrite_c))
        VALUE_VARLEN(value_cp_ctrl_point, gBleSig_CpControlPoint_d, (gPermissionFlagWritable_c), 15, 1, 0x00)
        CCCD(cccd_cp_ctrl_point)
    CHARACTERISTIC(char_cp_vector, gBleSig_CpVector_d, (gGattCharPropNotify_c))
        VALUE_VARLEN(value_cp_vector, gBleSig_CpVector_d, (gPermissionNone_c), 11, 1, 0x00)
        CCCD(cccd_cp_vector)

PRIMARY_SERVICE(service_battery, gBleSig_BatteryService_d)
    CHARACTERISTIC(char_battery_level, gBleSig_BatteryLevel_d, (gGattCharPropNotify_c | gGattCharPropRead_c))
        VALUE(value_battery_level, gBleSig_BatteryLevel_d, (gPermissionFlagReadable_c), 1, 0x5A)
        DESCRIPTOR(desc_bat_level, gBleSig_CharPresFormatDescriptor_d, (gPermissionFlagReadable_c), 7, 0x04, 0x00, 0xAD, 0x27, 0x01, 0x01, 0x00)
        CCCD(cccd_battery_level)

PRIMARY_SERVICE(service_device_info, gBleSig_DeviceInformationService_d)
    CHARACTERISTIC(char_manuf_name, gBleSig_ManufacturerNameString_d, (gGattCharPropRead_c) )
        VALUE(value_manuf_name, gBleSig_ManufacturerNameString_d, (gPermissionFlagReadable_c), sizeof(MANUFACTURER_NAME)-1, MANUFACTURER_NAME)
    CHARACTERISTIC(char_model_no, gBleSig_ModelNumberString_d, (gGattCharPropRead_c) )
        VALUE(value_model_no, gBleSig_ModelNumberString_d, (gPermissionFlagReadable_c), 8, "CPS Demo")
    CHARACTERISTIC(char_serial_no, gBleSig_SerialNumberString_d, (gGattCharPropRead_c) )
        VALUE(value_serial_no, gBleSig_SerialNumberString_d, (gPermissionFlagReadable_c), 7, "BLESN01")
    CHARACTERISTIC(char_hw_rev, gBleSig_HardwareRevisionString_d, (gGattCharPropRead_c) )
        VALUE(value_hw_rev, gBleSig_HardwareRevisionString_d, (gPermissionFlagReadable_c), sizeof(BOARD_NAME)-1, BOARD_NAME)
    CHARACTERISTIC(char_fw_rev, gBleSig_FirmwareRevisionString_d, (gGattCharPropRead_c) )
        VALUE(value_fw_rev, gBleSig_FirmwareRevisionString_d, (gPermissionFlagReadable_c), 5, "1.1.1")
    CHARACTERISTIC(char_sw_rev, gBleSig_SoftwareRevisionString_d, (gGattCharPropRead_c) )
        VALUE(value_sw_rev, gBleSig_SoftwareRevisionString_d, (gPermissionFlagReadable_c), 5, "1.1.4")
