# config to select component, the format is CONFIG_USE_${component}
# Please refer to cmake files below to get available components:
#  ${SdkRootDirPath}/devices/KW45B41Z83/all_lib_device.cmake

set(CONFIG_COMPILER gcc)
set(CONFIG_TOOLCHAIN armgcc)
set(CONFIG_USE_COMPONENT_CONFIGURATION false)
set(CONFIG_USE_utility_debug_console_lite true)
set(CONFIG_USE_utility_assert_lite true)
set(CONFIG_USE_driver_port true)
set(CONFIG_USE_driver_clock true)
set(CONFIG_USE_driver_lin true)
set(CONFIG_USE_driver_tpm true)
set(CONFIG_USE_driver_common true)
set(CONFIG_USE_device_KW45B41Z83_CMSIS true)
set(CONFIG_USE_component_lpuart_adapter true)
set(CONFIG_USE_driver_lpuart true)
set(CONFIG_USE_component_lists true)
set(CONFIG_USE_device_KW45B41Z83_startup true)
set(CONFIG_USE_driver_gpio true)
set(CONFIG_USE_driver_ccm32k true)
set(CONFIG_USE_driver_spc true)
set(CONFIG_USE_utilities_misc_utilities true)
set(CONFIG_USE_utility_str true)
set(CONFIG_USE_CMSIS_Include_core_cm true)
set(CONFIG_USE_device_KW45B41Z83_system true)
set(CONFIG_CORE cm33)
set(CONFIG_DEVICE KW45B41Z83)
set(CONFIG_BOARD kw45b41zevk)
set(CONFIG_KIT kw45b41zevk)
set(CONFIG_DEVICE_ID KW45B41Z83xxxA)
set(CONFIG_FPU SP_FPU)
set(CONFIG_DSP DSP)
