/*
 * Copyright 2019 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
 
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTG5 (number 52), D4[1]/PTG5_RED
  @{ */
#define BOARD_LED_RED_GPIO GPIOB            /*!<@brief GPIO device name: GPIOB */
#define BOARD_LED_RED_GPIO_PORT kGPIO_PORTG /*!<@brief PORTB GPIO port: PORTB */
#define BOARD_LED_RED_PORT PORTG            /*!<@brief PORT device name: PORTG */
#define BOARD_LED_RED_PIN 5U                /*!<@brief PORTG pin index: 5 */
                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
